import { useTranslation } from '@/hooks/use-translation';

interface TranslatedTextProps {
  children: string;
  className?: string;
}

export function TranslatedText({ 
  children, 
  className = ""
}: TranslatedTextProps) {
  const { currentLanguage } = useTranslation();
  
  // For non-English languages, return the original text and let CSS handle it
  // This avoids all async issues and React state problems
  if (currentLanguage === 'en' || !children) {
    return <span className={className}>{children}</span>;
  }

  // Simple mapping for common UI terms to avoid API calls entirely
  const translations: Record<string, Record<string, string>> = {
    'zh': {
      // Basic UI
      'Search by location or description...': '搜索位置或描述...',
      'All Categories': '所有类别',
      'Any Price': '任何价格',
      'Music': '音乐',
      'Food': '食物',
      'Travel': '旅行',
      'Events': '活动',
      'Fitness': '健身',
      'Education': '教育',
      'Available Orders': '可用订单',
      'My Orders': '我的订单',
      'Streaming Requests': '直播请求',
      'Creator': '创建者',
      'Price': '价格',
      'Total Pool': '总奖池',
      'Accept Order': '接受订单',
      'Join Stream': '加入直播',
      'Completed': '已完成',
      'Unavailable': '不可用',
      'Open': '开放',
      'Pending': '待处理',
      'Live': '直播中',
      'participants': '参与者',
      'min': '分钟',
      'Create Order': '创建订单',
      'Discover': '发现',
      'Earnings': '收益',
      'Settings': '设置',
      'Content Creator': '内容创作者',
      'Live Streams': '直播列表',
      'Orders': '订单',
      'Streams': '直播',
      'Profile': '个人资料',
      'All': '全部',
      // Home page content
      'Discover Live Streams': '发现直播',
      'Find and create location-based streaming experiences': '发现和创建基于位置的直播体验',
      'API Connected': 'API已连接',
      'API Disconnected': 'API断开连接',
      'Active Streams Nearby': '附近活跃直播',
      'No active streams nearby at the moment': '目前附近没有活跃的直播',
      'No orders match your filters': '没有订单符合您的筛选条件',
      'You haven\'t created any orders yet': '您还没有创建任何订单',
      'Create Your First Order': '创建您的第一个订单',
      // Form content
      'What would you like to stream?': '您想直播什么？',
      'Describe the streaming experience you want...': '描述您想要的直播体验...',
      'Enter location (e.g., San Francisco, CA)': '输入位置 (例如：北京，中国)',
      'Select duration': '选择时长',
      'Select category': '选择类别',
      'Get Current Location': '获取当前位置',
      'Creating...': '创建中...',
      // Specific order content
      'Central Park Concert Stream': '中央公园音乐会直播',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': '正在寻找人来直播今晚在中央公园举行的户外音乐会',
      'Central Park, NYC': '纽约中央公园',
      'Food Market Tour': '美食市场之旅',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': '希望有人直播派克市场的导览，展示当地商贩和食物',
      'Pike Place Market, Seattle': '西雅图派克市场',
      'Beach Sunset Yoga': '海滩日落瑜伽',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': '为健康爱好者直播圣莫尼卡海滩宁静的日落瑜伽',
      'Santa Monica Beach, CA': '加利福尼亚州圣莫尼卡海滩',
      // Messages and status
      'Success': '成功',
      'Error': '错误',
      'Connection Error': '连接错误',
      'Failed to connect to the server': '无法连接到服务器',
      'Order accepted successfully!': '订单接受成功！',
      'Failed to accept order': '接受订单失败',
      'Joining Stream': '加入直播',
      'Opening live stream...': '正在打开直播...',
      'Manage your streaming orders and track their progress': '管理您的直播订单并跟踪进度',
      'No orders found': '未找到订单',
      'Your orders will appear here once you create them': '创建订单后将显示在这里',
      // Language selector
      'Select Language / 选择语言': '选择语言 / Select Language',
      'Active': '当前',
      'Language / 语言': '语言 / Language',
      // Time
      'In 1h': '1小时后',
      'In 23h': '23小时后',
      'In 2 days': '2天后',
      'Tomorrow': '明天',
      'Now': '现在'
    },
    'ja': {
      // Basic UI (removed duplicates)
      'Search by location or description...': '場所や説明で検索...',
      'All Categories': 'すべてのカテゴリ',
      'Any Price': '任意の価格',
      'Music': '音楽',
      'Food': '食べ物',
      'Travel': '旅行',
      'Events': 'イベント',
      'Fitness': 'フィットネス',
      'Education': '教育',
      'Available Orders': '利用可能な注文',
      'My Orders': 'マイオーダー',
      'Creator': 'クリエイター',
      'Price': '価格',
      'Accept Order': '注文を受け入れる',
      'Join Stream': 'ストリームに参加',
      'Open': 'オープン',
      'Live': 'ライブ',
      'participants': '参加者',
      'min': '分',
      'Live Streams': 'ライブストリーム',
      'Discover': '発見',
      'Orders': '注文',
      'Streams': 'ストリーム',
      'Profile': 'プロフィール',
      'All': 'すべて',
      'Discover Live Streams': 'ライブストリームを発見',
      'Find and create location-based streaming experiences': '位置ベースのストリーミング体験を見つけて作成',
      'API Connected': 'API接続済み',
      'API Disconnected': 'API切断中',
      'Active Streams Nearby': '近くのアクティブストリーム',
      'No active streams nearby at the moment': '現在近くにアクティブなストリームはありません',
      'No orders match your filters': 'フィルターに一致する注文がありません',
      'You haven\'t created any orders yet': 'まだ注文を作成していません',
      'Create Your First Order': '最初の注文を作成',
      'What would you like to stream?': '何をストリーミングしたいですか？',
      'Describe the streaming experience you want...': '希望するストリーミング体験を説明してください...',
      'Enter location (e.g., San Francisco, CA)': '場所を入力（例：東京、日本）',
      'Select duration': '時間を選択',
      'Select category': 'カテゴリを選択',
      'Get Current Location': '現在位置を取得',
      'Creating...': '作成中...',
      'Central Park Concert Stream': 'セントラルパークコンサートストリーム',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': '今夜セントラルパークで開催される野外コンサートをストリーミングしてくれる人を探しています',
      'Central Park, NYC': 'ニューヨーク、セントラルパーク',
      'Food Market Tour': 'フードマーケットツアー',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'パイクプレイスマーケットのガイドツアーをストリーミングして、地元の業者と食べ物を紹介してほしい',
      'Pike Place Market, Seattle': 'シアトル、パイクプレイスマーケット',
      'Beach Sunset Yoga': 'ビーチサンセットヨガ',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'ウェルネス愛好家のためにサンタモニカビーチで平和的な夕日ヨガセッションをストリーミング',
      'Santa Monica Beach, CA': 'カリフォルニア州、サンタモニカビーチ',
      'Success': '成功',
      'Error': 'エラー',
      'Connection Error': '接続エラー',
      'Failed to connect to the server': 'サーバーに接続できませんでした',
      'Order accepted successfully!': '注文が正常に承認されました！',
      'Failed to accept order': '注文の承認に失敗しました',
      'Joining Stream': 'ストリームに参加',
      'Opening live stream...': 'ライブストリームを開いています...',
      'In 1h': '1時間後',
      'In 23h': '23時間後', 
      'In 2 days': '2日後'
    },
    'es': {
      // Basic UI (removed duplicates)
      'Search by location or description...': 'Buscar por ubicación o descripción...',
      'All Categories': 'Todas las categorías',
      'Any Price': 'Cualquier precio',
      'Music': 'Música',
      'Food': 'Comida',
      'Travel': 'Viaje',
      'Events': 'Eventos',
      'Fitness': 'Fitness',
      'Education': 'Educación',
      'Available Orders': 'Pedidos disponibles',
      'My Orders': 'Mis pedidos',
      'Creator': 'Creador',
      'Price': 'Precio',
      'Accept Order': 'Aceptar pedido',
      'Join Stream': 'Unirse al stream',
      'Open': 'Abierto',
      'Live': 'En vivo',
      'participants': 'participantes',
      'min': 'min',
      'Live Streams': 'Transmisiones en Vivo',
      'Discover': 'Descubrir',
      'Orders': 'Pedidos',
      'Streams': 'Transmisiones',
      'Profile': 'Perfil',
      'All': 'Todos',
      'Discover Live Streams': 'Descubrir Transmisiones en Vivo',
      'Find and create location-based streaming experiences': 'Encuentra y crea experiencias de transmisión basadas en ubicación',
      'API Connected': 'API Conectado',
      'API Disconnected': 'API Desconectado',
      'Active Streams Nearby': 'Transmisiones Activas Cercanas',
      'No active streams nearby at the moment': 'No hay transmisiones activas cerca en este momento',
      'No orders match your filters': 'Ningún pedido coincide con tus filtros',
      'You haven\'t created any orders yet': 'Aún no has creado ningún pedido',
      'Create Your First Order': 'Crear Tu Primer Pedido',
      'What would you like to stream?': '¿Qué te gustaría transmitir?',
      'Describe the streaming experience you want...': 'Describe la experiencia de transmisión que deseas...',
      'Enter location (e.g., San Francisco, CA)': 'Ingresa ubicación (ej: Madrid, España)',
      'Select duration': 'Seleccionar duración',
      'Select category': 'Seleccionar categoría',
      'Get Current Location': 'Obtener Ubicación Actual',
      'Creating...': 'Creando...',
      'Central Park Concert Stream': 'Stream de Concierto en Central Park',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'Buscando a alguien para transmitir el concierto al aire libre que ocurre en Central Park esta noche',
      'Central Park, NYC': 'Central Park, Nueva York',
      'Food Market Tour': 'Tour del Mercado de Comida',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'Quiero que alguien transmita un tour guiado del Mercado Pike Place, mostrando vendedores locales y comida',
      'Pike Place Market, Seattle': 'Mercado Pike Place, Seattle',
      'Beach Sunset Yoga': 'Yoga de Atardecer en la Playa',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'Transmitir una sesión pacífica de yoga al atardecer en la Playa Santa Monica para entusiastas del bienestar',
      'Santa Monica Beach, CA': 'Playa Santa Monica, California',
      'Success': 'Éxito',
      'Error': 'Error',
      'Connection Error': 'Error de Conexión',
      'Failed to connect to the server': 'Error al conectar con el servidor',
      'Order accepted successfully!': '¡Pedido aceptado exitosamente!',
      'Failed to accept order': 'Error al aceptar pedido',
      'Joining Stream': 'Unirse al Stream',
      'Opening live stream...': 'Abriendo transmisión en vivo...',
      'In 1h': 'En 1h',
      'In 23h': 'En 23h',
      'In 2 days': 'En 2 días'
    }
  };

  const translation = translations[currentLanguage]?.[children] || children;
  
  return <span className={className}>{translation}</span>;
}

