import { useTranslation } from '@/hooks/use-translation';

interface TranslatedTextProps {
  children: string;
  className?: string;
}

export function TranslatedText({ children, className }: TranslatedTextProps) {
  const { currentLanguage } = useTranslation();

  // Simple mapping for common UI terms to avoid API calls entirely
  const translations: Record<string, Record<string, string>> = {
    'zh': {
      // Basic UI
      'Search by location or description...': '搜索位置或描述...',
      'All Categories': '所有类别',
      'Any Price': '任何价格',
      'Music': '音乐',
      'Food': '食物',
      'Travel': '旅行',
      'Events': '活动',
      'Fitness': '健身',
      'Education': '教育',
      'Available Orders': '可用订单',
      'My Orders': '我的订单',
      'Streaming Requests': '直播请求',
      'Creator': '创建者',
      'Price': '价格',
      'Total Pool': '总奖池',
      'Accept Order': '接受订单',
      'Join Stream': '加入直播',
      'Completed': '已完成',
      'Unavailable': '不可用',
      'Open': '开放',
      'Pending': '待处理',
      'Live': '直播中',
      'Accepted': '已接受',
      'participants': '参与者',
      'min': '分钟',
      'Create Order': '创建订单',
      'Discover': '发现',
      'Earnings': '收益',
      'Settings': '设置',
      'Content Creator': '内容创作者',
      'Live Streams': '直播列表',
      'Orders': '订单',
      'Streams': '直播',
      'Profile': '个人资料',
      'All': '全部',
      'Discover Live Streams': '发现直播',
      'Find and create location-based streaming experiences': '发现和创建基于位置的直播体验',
      'API Connected': 'API已连接',
      'API Disconnected': 'API断开连接',
      'Active Streams Nearby': '附近活跃直播',
      'No active streams nearby at the moment': '目前附近没有活跃的直播',
      'No orders match your filters': '没有订单符合您的筛选条件',
      'You haven\'t created any orders yet': '您还没有创建任何订单',
      'Create Your First Order': '创建您的第一个订单',
      'What would you like to stream?': '您想直播什么？',
      'Describe the streaming experience you want...': '描述您想要的直播体验...',
      'Enter location (e.g., San Francisco, CA)': '输入位置 (例如：北京，中国)',
      'Select duration': '选择时长',
      'Select category': '选择类别',
      'Get Current Location': '获取当前位置',
      'Creating...': '创建中...',
      'Central Park Concert Stream': '中央公园音乐会直播',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': '正在寻找人来直播今晚在中央公园举行的户外音乐会',
      'Central Park, NYC': '纽约中央公园',
      'Food Market Tour': '美食市场之旅',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': '希望有人直播派克市场的导览，展示当地商贩和食物',
      'Pike Place Market, Seattle': '西雅图派克市场',
      'Beach Sunset Yoga': '海滩日落瑜伽',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': '为健康爱好者直播圣莫尼卡海滩宁静的日落瑜伽',
      'Santa Monica Beach, CA': '加利福尼亚州圣莫尼卡海滩',
      'Success': '成功',
      'Error': '错误',
      'Connection Error': '连接错误',
      'Failed to connect to the server': '无法连接到服务器',
      'Order accepted successfully!': '订单接受成功！',
      'Failed to accept order': '接受订单失败',
      'Joining Stream': '加入直播',
      'Opening live stream...': '正在打开直播...',
      'Manage your streaming orders and track their progress': '管理您的直播订单并跟踪进度',
      'No orders found': '未找到订单',
      'Your orders will appear here once you create them': '创建订单后将显示在这里',
      'Select Language / 选择语言': '选择语言 / Select Language',
      'Active': '当前',
      'Language / 语言': '语言 / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVP 平台',
      'Sarah Chen': '陈莎拉',
      'In 1h': '1小时后',
      'In 23h': '23小时后',
      'In 2 days': '2天后',
      'Tomorrow': '明天',
      'Now': '现在',
      'No pending orders': '没有待处理的订单',
      'No open orders': '没有开放的订单',
      'No accepted orders': '没有已接受的订单',
      'No live streams': '没有直播',
      'No completed orders': '没有已完成的订单'
    },
    'ja': {
      'Search by location or description...': '場所や説明で検索...',
      'All Categories': 'すべてのカテゴリ',
      'Any Price': '任意の価格',
      'Music': '音楽',
      'Food': '食べ物',
      'Travel': '旅行',
      'Events': 'イベント',
      'Fitness': 'フィットネス',
      'Education': '教育',
      'Available Orders': '利用可能な注文',
      'My Orders': 'マイオーダー',
      'Streaming Requests': 'ストリーミング要求',
      'Creator': 'クリエイター',
      'Price': '価格',
      'Total Pool': '総プール',
      'Accept Order': '注文を受け入れる',
      'Join Stream': 'ストリームに参加',
      'Open': 'オープン',
      'Live': 'ライブ',
      'Completed': '完了',
      'Unavailable': '利用不可',
      'Pending': '保留中',
      'Accepted': '承認済み',
      'participants': '参加者',
      'min': '分',
      'Live Streams': 'ライブストリーム',
      'Discover': '発見',
      'Orders': '注文',
      'Streams': 'ストリーム',
      'Profile': 'プロフィール',
      'All': 'すべて',
      'Earnings': '収益',
      'Settings': '設定',
      'Content Creator': 'コンテンツクリエイター',
      'Discover Live Streams': 'ライブストリームを発見',
      'Find and create location-based streaming experiences': '位置ベースのストリーミング体験を見つけて作成',
      'API Connected': 'API接続済み',
      'API Disconnected': 'API切断中',
      'Active Streams Nearby': '近くのアクティブストリーム',
      'No active streams nearby at the moment': '現在近くにアクティブなストリームはありません',
      'No orders match your filters': 'フィルターに一致する注文がありません',
      'You haven\'t created any orders yet': 'まだ注文を作成していません',
      'Create Your First Order': '最初の注文を作成',
      'What would you like to stream?': '何をストリーミングしたいですか？',
      'Describe the streaming experience you want...': '希望するストリーミング体験を説明してください...',
      'Enter location (e.g., San Francisco, CA)': '場所を入力（例：東京、日本）',
      'Select duration': '時間を選択',
      'Select category': 'カテゴリを選択',
      'Get Current Location': '現在位置を取得',
      'Creating...': '作成中...',
      'Central Park Concert Stream': 'セントラルパークコンサートストリーム',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': '今夜セントラルパークで開催される野外コンサートをストリーミングしてくれる人を探しています',
      'Central Park, NYC': 'ニューヨーク、セントラルパーク',
      'Food Market Tour': 'フードマーケットツアー',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'パイクプレイスマーケットのガイドツアーをストリーミングして、地元の業者と食べ物を紹介してほしい',
      'Pike Place Market, Seattle': 'シアトル、パイクプレイスマーケット',
      'Beach Sunset Yoga': 'ビーチサンセットヨガ',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'ウェルネス愛好家のためにサンタモニカビーチで平和的な夕日ヨガセッションをストリーミング',
      'Santa Monica Beach, CA': 'カリフォルニア州、サンタモニカビーチ',
      'Success': '成功',
      'Error': 'エラー',
      'Connection Error': '接続エラー',
      'Failed to connect to the server': 'サーバーに接続できませんでした',
      'Order accepted successfully!': '注文が正常に承認されました！',
      'Failed to accept order': '注文の承認に失敗しました',
      'Joining Stream': 'ストリームに参加',
      'Opening live stream...': 'ライブストリームを開いています...',
      'Language / 语言': '言語 / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVPプラットフォーム',
      'Sarah Chen': 'サラ・チェン',
      'In 1h': '1時間後',
      'In 23h': '23時間後', 
      'In 2 days': '2日後',
      'No pending orders': '保留中の注文がありません',
      'No open orders': 'オープンな注文がありません',
      'No accepted orders': '承認された注文がありません',
      'No live streams': 'ライブストリームがありません',
      'No completed orders': '完了した注文がありません'
    },
    'es': {
      'Search by location or description...': 'Buscar por ubicación o descripción...',
      'All Categories': 'Todas las categorías',
      'Any Price': 'Cualquier precio',
      'Music': 'Música',
      'Food': 'Comida',
      'Travel': 'Viaje',
      'Events': 'Eventos',
      'Fitness': 'Fitness',
      'Education': 'Educación',
      'Available Orders': 'Pedidos disponibles',
      'My Orders': 'Mis pedidos',
      'Streaming Requests': 'Solicitudes de transmisión',
      'Creator': 'Creador',
      'Price': 'Precio',
      'Total Pool': 'Pool total',
      'Accept Order': 'Aceptar pedido',
      'Join Stream': 'Unirse al stream',
      'Open': 'Abierto',
      'Live': 'En vivo',
      'Completed': 'Completado',
      'Unavailable': 'No disponible',
      'Pending': 'Pendiente',
      'Accepted': 'Aceptado',
      'participants': 'participantes',
      'min': 'min',
      'Live Streams': 'Transmisiones en Vivo',
      'Discover': 'Descubrir',
      'Orders': 'Pedidos',
      'Streams': 'Transmisiones',
      'Profile': 'Perfil',
      'All': 'Todos',
      'Earnings': 'Ganancias',
      'Settings': 'Configuración',
      'Content Creator': 'Creador de Contenido',
      'Discover Live Streams': 'Descubrir Transmisiones en Vivo',
      'Find and create location-based streaming experiences': 'Encuentra y crea experiencias de transmisión basadas en ubicación',
      'API Connected': 'API Conectado',
      'API Disconnected': 'API Desconectado',
      'Active Streams Nearby': 'Transmisiones Activas Cercanas',
      'No active streams nearby at the moment': 'No hay transmisiones activas cerca en este momento',
      'No orders match your filters': 'Ningún pedido coincide con tus filtros',
      'You haven\'t created any orders yet': 'Aún no has creado ningún pedido',
      'Create Your First Order': 'Crear Tu Primer Pedido',
      'What would you like to stream?': '¿Qué te gustaría transmitir?',
      'Describe the streaming experience you want...': 'Describe la experiencia de transmisión que deseas...',
      'Enter location (e.g., San Francisco, CA)': 'Ingresa ubicación (ej: Madrid, España)',
      'Select duration': 'Seleccionar duración',
      'Select category': 'Seleccionar categoría',
      'Get Current Location': 'Obtener Ubicación Actual',
      'Creating...': 'Creando...',
      'Central Park Concert Stream': 'Stream de Concierto en Central Park',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'Buscando a alguien para transmitir el concierto al aire libre que ocurre en Central Park esta noche',
      'Central Park, NYC': 'Central Park, Nueva York',
      'Food Market Tour': 'Tour del Mercado de Comida',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'Quiero que alguien transmita un tour guiado del Mercado Pike Place, mostrando vendedores locales y comida',
      'Pike Place Market, Seattle': 'Mercado Pike Place, Seattle',
      'Beach Sunset Yoga': 'Yoga de Atardecer en la Playa',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'Transmitir una sesión pacífica de yoga al atardecer en la Playa Santa Monica para entusiastas del bienestar',
      'Santa Monica Beach, CA': 'Playa Santa Monica, California',
      'Success': 'Éxito',
      'Error': 'Error',
      'Connection Error': 'Error de Conexión',
      'Failed to connect to the server': 'Error al conectar con el servidor',
      'Order accepted successfully!': '¡Pedido aceptado exitosamente!',
      'Failed to accept order': 'Error al aceptar pedido',
      'Joining Stream': 'Unirse al Stream',
      'Opening live stream...': 'Abriendo transmisión en vivo...',
      'Language / 语言': 'Idioma / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'Plataforma MVP',
      'Sarah Chen': 'Sarah Chen',
      'In 1h': 'En 1h',
      'In 23h': 'En 23h',
      'In 2 days': 'En 2 días',
      'No pending orders': 'No hay pedidos pendientes',
      'No open orders': 'No hay pedidos abiertos',
      'No accepted orders': 'No hay pedidos aceptados',
      'No live streams': 'No hay transmisiones en vivo',
      'No completed orders': 'No hay pedidos completados'
    },
    'ko': {
      'Search by location or description...': '위치 또는 설명으로 검색...',
      'All Categories': '모든 카테고리',
      'Any Price': '모든 가격',
      'Music': '음악',
      'Food': '음식',
      'Travel': '여행',
      'Events': '이벤트',
      'Fitness': '피트니스',
      'Education': '교육',
      'Available Orders': '이용 가능한 주문',
      'My Orders': '내 주문',
      'Streaming Requests': '스트리밍 요청',
      'Creator': '크리에이터',
      'Price': '가격',
      'Total Pool': '총 풀',
      'Accept Order': '주문 수락',
      'Join Stream': '스트림 참여',
      'Completed': '완료됨',
      'Unavailable': '이용 불가',
      'Open': '열림',
      'Pending': '대기 중',
      'Live': '라이브',
      'Accepted': '수락됨',
      'participants': '참가자',
      'min': '분',
      'Create Order': '주문 생성',
      'Discover': '발견',
      'Earnings': '수익',
      'Settings': '설정',
      'Content Creator': '콘텐츠 크리에이터',
      'Live Streams': '라이브 스트림',
      'Orders': '주문',
      'Streams': '스트림',
      'Profile': '프로필',
      'All': '모든',
      'Discover Live Streams': '라이브 스트림 발견',
      'Find and create location-based streaming experiences': '위치 기반 스트리밍 경험을 찾고 만드세요',
      'API Connected': 'API 연결됨',
      'API Disconnected': 'API 연결 끊김',
      'Active Streams Nearby': '근처 활성 스트림',
      'No active streams nearby at the moment': '현재 근처에 활성 스트림이 없습니다',
      'No orders match your filters': '필터와 일치하는 주문이 없습니다',
      'You haven\'t created any orders yet': '아직 주문을 생성하지 않았습니다',
      'Create Your First Order': '첫 번째 주문 생성',
      'What would you like to stream?': '무엇을 스트리밍하고 싶나요?',
      'Describe the streaming experience you want...': '원하는 스트리밍 경험을 설명하세요...',
      'Enter location (e.g., San Francisco, CA)': '위치 입력 (예: 서울, 한국)',
      'Select duration': '지속 시간 선택',
      'Select category': '카테고리 선택',
      'Get Current Location': '현재 위치 가져오기',
      'Creating...': '생성 중...',
      'Central Park Concert Stream': '센트럴 파크 콘서트 스트림',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': '오늘 저녁 센트럴 파크에서 열리는 야외 콘서트를 스트리밍할 사람을 찾고 있습니다',
      'Central Park, NYC': '뉴욕 센트럴 파크',
      'Food Market Tour': '음식 시장 투어',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': '파이크 플레이스 마켓의 가이드 투어를 스트리밍하여 현지 상인과 음식을 보여줄 사람을 원합니다',
      'Pike Place Market, Seattle': '시애틀 파이크 플레이스 마켓',
      'Beach Sunset Yoga': '해변 일몰 요가',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': '웰니스 애호가들을 위해 산타모니카 해변에서 평화로운 일몰 요가 세션을 스트리밍',
      'Santa Monica Beach, CA': '캘리포니아 산타모니카 해변',
      'Success': '성공',
      'Error': '오류',
      'Connection Error': '연결 오류',
      'Failed to connect to the server': '서버에 연결할 수 없습니다',
      'Order accepted successfully!': '주문이 성공적으로 승인되었습니다!',
      'Failed to accept order': '주문 승인 실패',
      'Joining Stream': '스트림 참여',
      'Opening live stream...': '라이브 스트림 열기...',
      'Language / 语言': '언어 / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVP 플랫폼',
      'Sarah Chen': '사라 첸',
      'In 1h': '1시간 후',
      'In 23h': '23시간 후',
      'In 2 days': '2일 후',
      'No pending orders': '대기 중인 주문이 없습니다',
      'No open orders': '열린 주문이 없습니다',
      'No accepted orders': '수락된 주문이 없습니다',
      'No live streams': '라이브 스트림이 없습니다',
      'No completed orders': '완료된 주문이 없습니다'
    },
    'fr': {
      'Search by location or description...': 'Rechercher par lieu ou description...',
      'All Categories': 'Toutes les catégories',
      'Any Price': 'Tous les prix',
      'Music': 'Musique',
      'Food': 'Nourriture',
      'Travel': 'Voyage',
      'Events': 'Événements',
      'Fitness': 'Fitness',
      'Education': 'Éducation',
      'Available Orders': 'Commandes disponibles',
      'My Orders': 'Mes commandes',
      'Streaming Requests': 'Demandes de streaming',
      'Creator': 'Créateur',
      'Price': 'Prix',
      'Total Pool': 'Pool total',
      'Accept Order': 'Accepter la commande',
      'Join Stream': 'Rejoindre le stream',
      'Completed': 'Terminé',
      'Unavailable': 'Indisponible',
      'Open': 'Ouvert',
      'Pending': 'En attente',
      'Live': 'En direct',
      'Accepted': 'Accepté',
      'participants': 'participants',
      'min': 'min',
      'Create Order': 'Créer une commande',
      'Discover': 'Découvrir',
      'Earnings': 'Revenus',
      'Settings': 'Paramètres',
      'Content Creator': 'Créateur de contenu',
      'Live Streams': 'Streams en direct',
      'Orders': 'Commandes',
      'Streams': 'Streams',
      'Profile': 'Profil',
      'All': 'Tous',
      'Discover Live Streams': 'Découvrir les streams en direct',
      'Find and create location-based streaming experiences': 'Trouvez et créez des expériences de streaming basées sur la localisation',
      'API Connected': 'API connectée',
      'API Disconnected': 'API déconnectée',
      'Active Streams Nearby': 'Streams actifs à proximité',
      'No active streams nearby at the moment': 'Aucun stream actif à proximité pour le moment',
      'No orders match your filters': 'Aucune commande ne correspond à vos filtres',
      'You haven\'t created any orders yet': 'Vous n\'avez pas encore créé de commandes',
      'Create Your First Order': 'Créer votre première commande',
      'What would you like to stream?': 'Que souhaitez-vous streamer ?',
      'Describe the streaming experience you want...': 'Décrivez l\'expérience de streaming que vous voulez...',
      'Enter location (e.g., San Francisco, CA)': 'Entrez l\'emplacement (ex: Paris, France)',
      'Select duration': 'Sélectionner la durée',
      'Select category': 'Sélectionner la catégorie',
      'Get Current Location': 'Obtenir la position actuelle',
      'Creating...': 'Création...',
      'Central Park Concert Stream': 'Stream Concert Central Park',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'Recherche quelqu\'un pour streamer le concert en plein air qui se déroule à Central Park ce soir',
      'Central Park, NYC': 'Central Park, New York',
      'Food Market Tour': 'Tour du Marché Alimentaire',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'Je veux que quelqu\'un stream une visite guidée du Pike Place Market, présentant les vendeurs locaux et la nourriture',
      'Pike Place Market, Seattle': 'Pike Place Market, Seattle',
      'Beach Sunset Yoga': 'Yoga Coucher de Soleil sur la Plage',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'Streamez une session de yoga paisible au coucher du soleil à Santa Monica Beach pour les passionnés de bien-être',
      'Santa Monica Beach, CA': 'Plage de Santa Monica, Californie',
      'Language / 语言': 'Langue / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'Plateforme MVP',
      'Sarah Chen': 'Sarah Chen',
      'In 1h': 'Dans 1h',
      'In 23h': 'Dans 23h',
      'In 2 days': 'Dans 2 jours',
      'No pending orders': 'Aucune commande en attente',
      'No open orders': 'Aucune commande ouverte',
      'No accepted orders': 'Aucune commande acceptée',
      'No live streams': 'Aucun stream en direct',
      'No completed orders': 'Aucune commande terminée'
    },
    'de': {
      'Search by location or description...': 'Nach Ort oder Beschreibung suchen...',
      'All Categories': 'Alle Kategorien',
      'Any Price': 'Jeder Preis',
      'Music': 'Musik',
      'Food': 'Essen',
      'Travel': 'Reisen',
      'Events': 'Veranstaltungen',
      'Fitness': 'Fitness',
      'Education': 'Bildung',
      'Available Orders': 'Verfügbare Bestellungen',
      'My Orders': 'Meine Bestellungen',
      'Streaming Requests': 'Streaming-Anfragen',
      'Creator': 'Ersteller',
      'Price': 'Preis',
      'Total Pool': 'Gesamtpool',
      'Accept Order': 'Bestellung annehmen',
      'Join Stream': 'Stream beitreten',
      'Completed': 'Abgeschlossen',
      'Unavailable': 'Nicht verfügbar',
      'Open': 'Offen',
      'Pending': 'Ausstehend',
      'Live': 'Live',
      'Accepted': 'Angenommen',
      'participants': 'Teilnehmer',
      'min': 'Min',
      'Create Order': 'Bestellung erstellen',
      'Discover': 'Entdecken',
      'Orders': 'Bestellungen',
      'Streams': 'Streams',
      'Profile': 'Profil',
      'All': 'Alle',
      'Live Streams': 'Live-Streams',
      'Earnings': 'Einnahmen',
      'Settings': 'Einstellungen',
      'Content Creator': 'Content-Ersteller',
      'Central Park Concert Stream': 'Central Park Konzert Stream',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'Suche jemanden, der das Outdoor-Konzert im Central Park heute Abend streamt',
      'Central Park, NYC': 'Central Park, New York',
      'Food Market Tour': 'Lebensmittelmarkt-Tour',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'Möchte, dass jemand eine geführte Tour durch den Pike Place Market streamt, mit lokalen Händlern und Essen',
      'Pike Place Market, Seattle': 'Pike Place Market, Seattle',
      'Beach Sunset Yoga': 'Strand Sonnenuntergang Yoga',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'Streame eine friedliche Sonnenuntergang-Yoga-Session am Santa Monica Beach für Wellness-Enthusiasten',
      'Santa Monica Beach, CA': 'Santa Monica Beach, Kalifornien',
      'Language / 语言': 'Sprache / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVP-Plattform',
      'Sarah Chen': 'Sarah Chen',
      'In 1h': 'In 1 Std',
      'In 23h': 'In 23 Std',
      'In 2 days': 'In 2 Tagen',
      'No pending orders': 'Keine ausstehenden Bestellungen',
      'No open orders': 'Keine offenen Bestellungen',
      'No accepted orders': 'Keine angenommenen Bestellungen',
      'No live streams': 'Keine Live-Streams',
      'No completed orders': 'Keine abgeschlossenen Bestellungen'
    },
    'ru': {
      'Search by location or description...': 'Поиск по местоположению или описанию...',
      'All Categories': 'Все категории',
      'Any Price': 'Любая цена',
      'Music': 'Музыка',
      'Food': 'Еда',
      'Travel': 'Путешествия',
      'Events': 'События',
      'Fitness': 'Фитнес',
      'Education': 'Образование',
      'Available Orders': 'Доступные заказы',
      'My Orders': 'Мои заказы',
      'Streaming Requests': 'Запросы на стриминг',
      'Creator': 'Создатель',
      'Price': 'Цена',
      'Total Pool': 'Общий пул',
      'Accept Order': 'Принять заказ',
      'Join Stream': 'Присоединиться к стриму',
      'Completed': 'Завершено',
      'Unavailable': 'Недоступно',
      'Open': 'Открыт',
      'Pending': 'Ожидание',
      'Live': 'В эфире',
      'Accepted': 'Принято',
      'participants': 'участники',
      'min': 'мин',
      'Create Order': 'Создать заказ',
      'Discover': 'Обнаружить',
      'Orders': 'Заказы',
      'Streams': 'Стримы',
      'Profile': 'Профиль',
      'All': 'Все',
      'Live Streams': 'Прямые трансляции',
      'Earnings': 'Доходы',
      'Settings': 'Настройки',
      'Content Creator': 'Создатель контента',
      'Central Park Concert Stream': 'Стрим концерта в Центральном парке',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'Ищу кого-то для трансляции концерта под открытым небом в Центральном парке сегодня вечером',
      'Central Park, NYC': 'Центральный парк, Нью-Йорк',
      'Food Market Tour': 'Тур по продуктовому рынку',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'Хочу, чтобы кто-то транслировал экскурсию по рынку Пайк-Плейс, показывая местных продавцов и еду',
      'Pike Place Market, Seattle': 'Рынок Пайк-Плейс, Сиэтл',
      'Beach Sunset Yoga': 'Йога на закате на пляже',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'Транслируйте спокойную сессию йоги на закате на пляже Санта-Моника для любителей wellness',
      'Santa Monica Beach, CA': 'Пляж Санта-Моника, Калифорния',
      'Language / 语言': 'Язык / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVP Платформа',
      'Sarah Chen': 'Сара Чен',
      'In 1h': 'Через 1 ч',
      'In 23h': 'Через 23 ч',
      'In 2 days': 'Через 2 дня',
      'No pending orders': 'Нет заказов в ожидании',
      'No open orders': 'Нет открытых заказов',
      'No accepted orders': 'Нет принятых заказов',
      'No live streams': 'Нет прямых трансляций',
      'No completed orders': 'Нет завершенных заказов'
    },
    'pt': {
      'Search by location or description...': 'Pesquisar por localização ou descrição...',
      'All Categories': 'Todas as categorias',
      'Any Price': 'Qualquer preço',
      'Music': 'Música',
      'Food': 'Comida',
      'Travel': 'Viagem',
      'Events': 'Eventos',
      'Fitness': 'Fitness',
      'Education': 'Educação',
      'Available Orders': 'Pedidos disponíveis',
      'My Orders': 'Meus pedidos',
      'Streaming Requests': 'Solicitações de streaming',
      'Creator': 'Criador',
      'Price': 'Preço',
      'Total Pool': 'Pool total',
      'Accept Order': 'Aceitar pedido',
      'Join Stream': 'Participar do stream',
      'Open': 'Aberto',
      'Live': 'Ao vivo',
      'Completed': 'Completado',
      'Unavailable': 'Indisponível',
      'Pending': 'Pendente',
      'Accepted': 'Aceito',
      'participants': 'participantes',
      'min': 'min',
      'Create Order': 'Criar pedido',
      'Discover': 'Descobrir',
      'Orders': 'Pedidos',
      'Streams': 'Streams',
      'Profile': 'Perfil',
      'All': 'Todos',
      'Live Streams': 'Transmissões ao vivo',
      'Earnings': 'Ganhos',
      'Settings': 'Configurações',
      'Content Creator': 'Criador de Conteúdo',
      'Language / 语言': 'Idioma / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'Plataforma MVP',
      'Sarah Chen': 'Sarah Chen',
      'In 1h': 'Em 1h',
      'In 23h': 'Em 23h',
      'In 2 days': 'Em 2 dias',
      'No pending orders': 'Nenhum pedido pendente',
      'No open orders': 'Nenhum pedido aberto',
      'No accepted orders': 'Nenhum pedido aceito',
      'No live streams': 'Nenhuma transmissão ao vivo',
      'No completed orders': 'Nenhum pedido concluído'
    },
    'it': {
      'Search by location or description...': 'Cerca per posizione o descrizione...',
      'All Categories': 'Tutte le categorie',
      'Any Price': 'Qualsiasi prezzo',
      'Music': 'Musica',
      'Food': 'Cibo',
      'Travel': 'Viaggio',
      'Events': 'Eventi',
      'Fitness': 'Fitness',
      'Education': 'Educazione',
      'Available Orders': 'Ordini disponibili',
      'My Orders': 'I miei ordini',
      'Streaming Requests': 'Richieste di streaming',
      'Creator': 'Creatore',
      'Price': 'Prezzo',
      'Total Pool': 'Pool totale',
      'Accept Order': 'Accetta ordine',
      'Join Stream': 'Unisciti al stream',
      'Open': 'Aperto',
      'Live': 'In diretta',
      'Completed': 'Completato',
      'Unavailable': 'Non disponibile',
      'Pending': 'In sospeso',
      'Accepted': 'Accettato',
      'participants': 'partecipanti',
      'min': 'min',
      'Create Order': 'Crea ordine',
      'Discover': 'Scopri',
      'Orders': 'Ordini',
      'Streams': 'Stream',
      'Profile': 'Profilo',
      'All': 'Tutti',
      'Live Streams': 'Stream dal vivo',
      'Earnings': 'Guadagni',
      'Settings': 'Impostazioni',
      'Content Creator': 'Creatore di contenuti',
      'Language / 语言': 'Lingua / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'Piattaforma MVP',
      'Sarah Chen': 'Sarah Chen',
      'In 1h': 'Tra 1h',
      'In 23h': 'Tra 23h',
      'In 2 days': 'Tra 2 giorni',
      'No pending orders': 'Nessun ordine in sospeso',
      'No open orders': 'Nessun ordine aperto',
      'No accepted orders': 'Nessun ordine accettato',
      'No live streams': 'Nessun stream dal vivo',
      'No completed orders': 'Nessun ordine completato'
    },
    'ar': {
      'Search by location or description...': 'البحث حسب الموقع أو الوصف...',
      'All Categories': 'جميع الفئات',
      'Any Price': 'أي سعر',
      'Music': 'موسيقى',
      'Food': 'طعام',
      'Travel': 'سفر',
      'Events': 'أحداث',
      'Fitness': 'لياقة',
      'Education': 'تعليم',
      'Available Orders': 'الطلبات المتاحة',
      'My Orders': 'طلباتي',
      'Streaming Requests': 'طلبات البث',
      'Creator': 'منشئ',
      'Price': 'سعر',
      'Total Pool': 'المجموع الكلي',
      'Accept Order': 'قبول الطلب',
      'Join Stream': 'انضم للبث',
      'Open': 'مفتوح',
      'Live': 'مباشر',
      'Completed': 'مكتمل',
      'Unavailable': 'غير متوفر',
      'Pending': 'قيد الانتظار',
      'Accepted': 'مقبول',
      'participants': 'مشاركين',
      'min': 'دقيقة',
      'Create Order': 'إنشاء طلب',
      'Discover': 'اكتشف',
      'Orders': 'الطلبات',
      'Streams': 'البث',
      'Profile': 'الملف الشخصي',
      'All': 'الكل',
      'Live Streams': 'البث المباشر',
      'Earnings': 'الأرباح',
      'Settings': 'الإعدادات',
      'Content Creator': 'منشئ المحتوى',
      'Language / 语言': 'اللغة / Language',
      'TapLive': 'تاب لايف',
      'MVP Platform': 'منصة MVP',
      'Sarah Chen': 'سارة تشين',
      'In 1h': 'خلال ساعة',
      'In 23h': 'خلال 23 ساعة',
      'In 2 days': 'خلال يومين',
      'No pending orders': 'لا توجد طلبات معلقة',
      'No open orders': 'لا توجد طلبات مفتوحة',
      'No accepted orders': 'لا توجد طلبات مقبولة',
      'No live streams': 'لا يوجد بث مباشر',
      'No completed orders': 'لا توجد طلبات مكتملة'
    },
    'hi': {
      'Search by location or description...': 'स्थान या विवरण द्वारा खोजें...',
      'All Categories': 'सभी श्रेणियां',
      'Any Price': 'कोई भी कीमत',
      'Music': 'संगीत',
      'Food': 'भोजन',
      'Travel': 'यात्रा',
      'Events': 'घटनाएं',
      'Fitness': 'फिटनेस',
      'Education': 'शिक्षा',
      'Available Orders': 'उपलब्ध ऑर्डर',
      'My Orders': 'मेरे ऑर्डर',
      'Streaming Requests': 'स्ट्रीमिंग अनुरोध',
      'Creator': 'निर्माता',
      'Price': 'कीमत',
      'Total Pool': 'कुल पूल',
      'Accept Order': 'ऑर्डर स्वीकार करें',
      'Join Stream': 'स्ट्रीम में शामिल हों',
      'Open': 'खुला',
      'Live': 'लाइव',
      'Completed': 'पूर्ण',
      'Unavailable': 'अनुपलब्ध',
      'Pending': 'लंबित',
      'Accepted': 'स्वीकृत',
      'participants': 'प्रतिभागी',
      'min': 'मिनट',
      'Create Order': 'ऑर्डर बनाएं',
      'Discover': 'खोजें',
      'Orders': 'ऑर्डर',
      'Streams': 'स्ट्रीम',
      'Profile': 'प्रोफ़ाइल',
      'All': 'सभी',
      'Content Creator': 'सामग्री निर्माता',
      'Live Streams': 'लाइव स्ट्रीम',
      'Settings': 'सेटिंग्स',
      'Earnings': 'कमाई',
      'Discover Live Streams': 'लाइव स्ट्रीम खोजें',
      'Find and create location-based streaming experiences': 'स्थान-आधारित स्ट्रीमिंग अनुभव खोजें और बनाएं',
      'API Connected': 'API कनेक्टेड',
      'API Disconnected': 'API डिस्कनेक्टेड',
      'Active Streams Nearby': 'आस-पास सक्रिय स्ट्रीम',
      'No active streams nearby at the moment': 'इस समय आस-पास कोई सक्रिय स्ट्रीम नहीं',
      'No orders match your filters': 'आपके फिल्टर से कोई ऑर्डर मेल नहीं खाता',
      'You haven\'t created any orders yet': 'आपने अभी तक कोई ऑर्डर नहीं बनाया है',
      'Create Your First Order': 'अपना पहला ऑर्डर बनाएं',
      'What would you like to stream?': 'आप क्या स्ट्रीम करना चाहेंगे?',
      'Describe the streaming experience you want...': 'जो स्ट्रीमिंग अनुभव आप चाहते हैं उसका वर्णन करें...',
      'Enter location (e.g., San Francisco, CA)': 'स्थान दर्ज करें (जैसे: दिल्ली, भारत)',
      'Select duration': 'अवधि चुनें',
      'Select category': 'श्रेणी चुनें',
      'Get Current Location': 'वर्तमान स्थान प्राप्त करें',
      'Creating...': 'बना रहे हैं...',
      'Central Park Concert Stream': 'सेंट्रल पार्क कॉन्सर्ट स्ट्रीम',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'आज शाम सेंट्रल पार्क में हो रहे आउटडोर कॉन्सर्ट को स्ट्रीम करने के लिए किसी की तलाश',
      'Central Park, NYC': 'सेंट्रल पार्क, न्यूयॉर्क',
      'Food Market Tour': 'फूड मार्केट टूर',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'पाइक प्लेस मार्केट का गाइडेड टूर स्ट्रीम करने के लिए किसी को चाहिए, जो स्थानीय विक्रेताओं और भोजन को दिखाए',
      'Pike Place Market, Seattle': 'पाइक प्लेस मार्केट, सिएटल',
      'Beach Sunset Yoga': 'बीच सनसेट योग',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'स्वास्थ्य उत्साही लोगों के लिए सांता मोनिका बीच पर शांतिपूर्ण सनसेट योग सत्र स्ट्रीम करें',
      'Santa Monica Beach, CA': 'सांता मोनिका बीच, कैलिफोर्निया',
      'Success': 'सफलता',
      'Error': 'त्रुटि',
      'Connection Error': 'कनेक्शन त्रुटि',
      'Failed to connect to the server': 'सर्वर से कनेक्ट करने में विफल',
      'Order accepted successfully!': 'ऑर्डर सफलतापूर्वक स्वीकार किया गया!',
      'Failed to accept order': 'ऑर्डर स्वीकार करने में विफल',
      'Joining Stream': 'स्ट्रीम में शामिल हो रहे हैं',
      'Opening live stream...': 'लाइव स्ट्रीम खोल रहे हैं...',
      'Manage your streaming orders and track their progress': 'अपने स्ट्रीमिंग ऑर्डर का प्रबंधन करें और उनकी प्रगति को ट्रैक करें',
      'No orders found': 'कोई ऑर्डर नहीं मिला',
      'Your orders will appear here once you create them': 'आपके ऑर्डर बनाने के बाद यहाँ दिखाई देंगे',
      'Select Language / 选择语言': 'भाषा चुनें / Select Language',
      'Active': 'सक्रिय',
      'Language / 语言': 'भाषा / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVP प्लेटफॉर्म',
      'Sarah Chen': 'सारा चेन',
      'Tomorrow': 'कल',
      'Now': 'अब',
      'In 1h': '1 घंटे में',
      'In 23h': '23 घंटे में',
      'In 2 days': '2 दिन में',
      'No pending orders': 'कोई लंबित ऑर्डर नहीं',
      'No open orders': 'कोई खुले ऑर्डर नहीं',
      'No accepted orders': 'कोई स्वीकृत ऑर्डर नहीं',
      'No live streams': 'कोई लाइव स्ट्रीम नहीं',
      'No completed orders': 'कोई पूर्ण ऑर्डर नहीं'
    }
  };

  const translation = translations[currentLanguage]?.[children] || children;
  
  return <span className={className}>{translation}</span>;
}