import { useTranslation } from '@/hooks/use-translation';

interface TranslatedTextProps {
  children: string;
  className?: string;
}

// Simple mapping for common UI terms to avoid API calls entirely
const translations: Record<string, Record<string, string>> = {
    'en': {
      // Basic UI
      'Search by location or description...': 'Search by location or description...',
      'All Categories': 'All Categories',
      'Any Price': 'Any Price',
      'Music': 'Music',
      'Food': 'Food',
      'Travel': 'Travel',
      'Events': 'Events',
      'Fitness': 'Fitness',
      'Education': 'Education',
      'Available Orders': 'Available Orders',
      'My Orders': 'My Orders',
      'Streaming Requests': 'Streaming Requests',
      'Creator': 'Creator',
      'Price': 'Price',
      'Total Pool': 'Total Pool',
      'Accept Order': 'Accept Order',
      'Join Stream': 'Join Stream',
      'Completed': 'Completed',
      'Unavailable': 'Unavailable',
      'Open': 'Open',
      'Pending': 'Pending',
      'Live': 'Live',
      'Accepted': 'Accepted',
      'participants': 'participants',
      'min': 'min',
      'Create Order': 'Create Order',
      'Discover': 'Discover',
      'Earnings': 'Earnings',
      'Settings': 'Settings',
      'Content Creator': 'Content Creator',
      'Live Streams': 'Live Streams',
      'Orders': 'Orders',
      'Streams': 'Streams',
      'Profile': 'Profile',
      'All': 'All',
      'Discover Live Streams': 'Discover Live Streams',
      'Find and create location-based streaming experiences': 'Find and create location-based streaming experiences',
      'API Connected': 'API Connected',
      'API Disconnected': 'API Disconnected',
      'Active Streams Nearby': 'Active Streams Nearby',
      'No active streams nearby at the moment': 'No active streams nearby at the moment',
      'No orders match your filters': 'No orders match your filters',
      'You haven\'t created any orders yet': 'You haven\'t created any orders yet',
      'Create Your First Order': 'Create Your First Order',
      'What would you like to stream?': 'What would you like to stream?',
      'Describe the streaming experience you want...': 'Describe the streaming experience you want...',
      'Enter location (e.g., San Francisco, CA)': 'Enter location (e.g., San Francisco, CA)',
      'Select duration': 'Select duration',
      'Select category': 'Select category',
      'Get Current Location': 'Get Current Location',
      'Creating...': 'Creating...',
      'Central Park Concert Stream': 'Central Park Concert Stream',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'Looking for someone to stream the outdoor concert happening at Central Park this evening',
      'Central Park, NYC': 'Central Park, NYC',
      'Food Market Tour': 'Food Market Tour',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food',
      'Pike Place Market, Seattle': 'Pike Place Market, Seattle',
      'Beach Sunset Yoga': 'Beach Sunset Yoga',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts',
      'Santa Monica Beach, CA': 'Santa Monica Beach, CA',
      'Success': 'Success',
      'Error': 'Error',
      'Connection Error': 'Connection Error',
      'Failed to connect to the server': 'Failed to connect to the server',
      'Order accepted successfully!': 'Order accepted successfully!',
      'Failed to accept order': 'Failed to accept order',
      'Joining Stream': 'Joining Stream',
      'Opening live stream...': 'Opening live stream...',
      'Manage your streaming orders and track their progress': 'Manage your streaming orders and track their progress',
      'No orders found': 'No orders found',
      'Your orders will appear here once you create them': 'Your orders will appear here once you create them',
      'Select Language / 选择语言': 'Select Language / 选择语言',
      'Active': 'Active',
      'Language / 语言': 'Language / 语言',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVP Platform',
      'Sarah Chen': 'Sarah Chen',
      'In 1h': 'In 1h',
      'In 23h': 'In 23h',
      'In 2 days': 'In 2 days',
      'Tomorrow': 'Tomorrow',
      'Now': 'Now',
      'No pending orders': 'No pending orders',
      'No open orders': 'No open orders',
      'No accepted orders': 'No accepted orders',
      'No live streams': 'No live streams',
      'No completed orders': 'No completed orders',
      
      // Settings page
      'Manage your account preferences and streaming settings': 'Manage your account preferences and streaming settings',
      'Profile Settings': 'Profile Settings',
      'Update your personal information and profile details': 'Update your personal information and profile details',
      'First Name': 'First Name',
      'Last Name': 'Last Name',
      'Email': 'Email',
      'Bio': 'Bio',
      'Tell viewers about yourself...': 'Tell viewers about yourself...',
      'Professional content creator specializing in travel and lifestyle streaming.': 'Professional content creator specializing in travel and lifestyle streaming.',
      'Save Profile': 'Save Profile',
      'Streaming Settings': 'Streaming Settings',
      'Configure your default streaming preferences': 'Configure your default streaming preferences',
      'Default Stream Duration': 'Default Stream Duration',
      'Default Category': 'Default Category',
      'Auto-start recording': 'Auto-start recording',
      'Automatically record all your streams': 'Automatically record all your streams',
      'HD Quality': 'HD Quality',
      'Stream in high definition (uses more data)': 'Stream in high definition (uses more data)',
      'Notifications': 'Notifications',
      'Choose what notifications you want to receive': 'Choose what notifications you want to receive',
      'New Order Alerts': 'New Order Alerts',
      'Get notified when someone places a new order': 'Get notified when someone places a new order',
      'Stream Reminders': 'Stream Reminders',
      'Remind you before scheduled streams': 'Remind you before scheduled streams',
      'Payment Notifications': 'Payment Notifications',
      'Get notified when you receive payments': 'Get notified when you receive payments',
      'Marketing Emails': 'Marketing Emails',
      'Receive tips and updates about the platform': 'Receive tips and updates about the platform',
      'Language & Region': 'Language & Region',
      'Set your language and regional preferences': 'Set your language and regional preferences',
      'Timezone': 'Timezone',
      'Privacy & Security': 'Privacy & Security',
      'Manage your privacy settings and account security': 'Manage your privacy settings and account security',
      'Profile Visibility': 'Profile Visibility',
      'Make your profile visible to other users': 'Make your profile visible to other users',
      'Location Sharing': 'Location Sharing',
      'Allow sharing your location during streams': 'Allow sharing your location during streams',
      'Change Password': 'Change Password',
      'Delete Account': 'Delete Account',
      
      // Earnings page
      'Track your streaming revenue and performance': 'Track your streaming revenue and performance',
      'Total Earnings': 'Total Earnings',
      'All time': 'All time',
      'This Month': 'This Month',
      '+12% from last month': '+12% from last month',
      'Completed Streams': 'Completed Streams',
      'Average Rating': 'Average Rating',
      'From customer reviews': 'From customer reviews',
      'Recent Earnings': 'Recent Earnings',
      'Your latest completed streaming sessions': 'Your latest completed streaming sessions',
      
      // Streams page
      'Watch and manage your live streaming sessions': 'Watch and manage your live streaming sessions',
      'Live Now': 'Live Now',
      'Watch Stream': 'Watch Stream',
      'No Live Streams': 'No Live Streams',
      'No streams are currently live. Check back later!': 'No streams are currently live. Check back later!',
      'Upcoming Streams': 'Upcoming Streams',
      'Scheduled': 'Scheduled',
      'Set Reminder': 'Set Reminder',
      'No Upcoming Streams': 'No Upcoming Streams',
      'No streams are scheduled yet.': 'No streams are scheduled yet.',
      'Times Square Night Walk': 'Times Square Night Walk',
      'Exploring the bright lights of NYC': 'Exploring the bright lights of NYC',
      'Times Square, NYC': 'Times Square, NYC',
      'Golden Gate Bridge View': 'Golden Gate Bridge View',
      'Beautiful sunset view from Marin': 'Beautiful sunset view from Marin',
      'San Francisco, CA': 'San Francisco, CA',
      'Central Park Concert': 'Central Park Concert',
      'Live jazz performance in the park': 'Live jazz performance in the park'
    },
    'zh': {
      // Basic UI
      'Search by location or description...': '搜索位置或描述...',
      'All Categories': '所有类别',
      'Any Price': '任何价格',
      'Music': '音乐',
      'Food': '食物',
      'Travel': '旅行',
      'Events': '活动',
      'Fitness': '健身',
      'Education': '教育',
      'Available Orders': '可用订单',
      'My Orders': '我的订单',
      'Streaming Requests': '直播请求',
      'Creator': '创建者',
      'Price': '价格',
      'Total Pool': '总奖池',
      'Accept Order': '接受订单',
      'Join Stream': '加入直播',
      'Completed': '已完成',
      'Unavailable': '不可用',
      'Open': '开放',
      'Pending': '待处理',
      'Live': '直播中',
      'Accepted': '已接受',
      'participants': '参与者',
      'min': '分钟',
      'Create Order': '创建订单',
      'Discover': '发现',
      'Earnings': '收益',
      'Settings': '设置',
      'Content Creator': '内容创作者',
      'Live Streams': '直播列表',
      'Orders': '订单',
      'Streams': '直播',
      'Profile': '个人资料',
      'All': '全部',
      'Discover Live Streams': '发现直播',
      'Find and create location-based streaming experiences': '发现和创建基于位置的直播体验',
      'API Connected': 'API已连接',
      'API Disconnected': 'API断开连接',
      'Active Streams Nearby': '附近活跃直播',
      'No active streams nearby at the moment': '目前附近没有活跃的直播',
      'No orders match your filters': '没有订单符合您的筛选条件',
      'You haven\'t created any orders yet': '您还没有创建任何订单',
      'Create Your First Order': '创建您的第一个订单',
      'What would you like to stream?': '您想直播什么？',
      'Describe the streaming experience you want...': '描述您想要的直播体验...',
      'Enter location (e.g., San Francisco, CA)': '输入位置 (例如：北京，中国)',
      'Select duration': '选择时长',
      'Select category': '选择类别',
      'Get Current Location': '获取当前位置',
      'Creating...': '创建中...',
      'Central Park Concert Stream': '中央公园音乐会直播',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': '正在寻找人来直播今晚在中央公园举行的户外音乐会',
      'Central Park, NYC': '纽约中央公园',
      'Food Market Tour': '美食市场之旅',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': '希望有人直播派克市场的导览，展示当地商贩和食物',
      'Pike Place Market, Seattle': '西雅图派克市场',
      'Beach Sunset Yoga': '海滩日落瑜伽',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': '为健康爱好者直播圣莫尼卡海滩宁静的日落瑜伽',
      'Santa Monica Beach, CA': '加利福尼亚州圣莫尼卡海滩',
      'Success': '成功',
      'Error': '错误',
      'Connection Error': '连接错误',
      'Failed to connect to the server': '无法连接到服务器',
      'Order accepted successfully!': '订单接受成功！',
      'Failed to accept order': '接受订单失败',
      'Joining Stream': '加入直播',
      'Opening live stream...': '正在打开直播...',
      'Manage your streaming orders and track their progress': '管理您的直播订单并跟踪进度',
      'No orders found': '未找到订单',
      'Your orders will appear here once you create them': '创建订单后将显示在这里',
      'Select Language / 选择语言': '选择语言 / Select Language',
      'Active': '当前',
      'Language / 语言': '语言 / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVP 平台',
      'Sarah Chen': '陈莎拉',
      'In 1h': '1小时后',
      'In 23h': '23小时后',
      'In 2 days': '2天后',
      'Tomorrow': '明天',
      'Now': '现在',
      'No pending orders': '没有待处理的订单',
      'No open orders': '没有开放的订单',
      'No accepted orders': '没有已接受的订单',
      'No live streams': '没有直播',
      'No completed orders': '没有已完成的订单',
      
      // Settings page
      'Manage your account preferences and streaming settings': '管理您的账户偏好和直播设置',
      'Profile Settings': '个人资料设置',
      'Update your personal information and profile details': '更新您的个人信息和个人资料详情',
      'First Name': '名字',
      'Last Name': '姓氏',
      'Email': '邮箱',
      'Bio': '个人简介',
      'Tell viewers about yourself...': '向观众介绍一下你自己...',
      'Professional content creator specializing in travel and lifestyle streaming.': '专业内容创作者，专注于旅行和生活方式直播。',
      'Save Profile': '保存资料',
      'Streaming Settings': '直播设置',
      'Configure your default streaming preferences': '配置您的默认直播偏好',
      'Default Stream Duration': '默认直播时长',
      'Default Category': '默认分类',
      'Auto-start recording': '自动开始录制',
      'Automatically record all your streams': '自动录制您的所有直播',
      'HD Quality': '高清质量',
      'Stream in high definition (uses more data)': '高清直播（使用更多数据）',
      'Notifications': '通知',
      'Choose what notifications you want to receive': '选择您想要接收的通知',
      'New Order Alerts': '新订单提醒',
      'Get notified when someone places a new order': '有人下新订单时获得通知',
      'Stream Reminders': '直播提醒',
      'Remind you before scheduled streams': '在预定直播前提醒您',
      'Payment Notifications': '支付通知',
      'Get notified when you receive payments': '收到付款时获得通知',
      'Marketing Emails': '营销邮件',
      'Receive tips and updates about the platform': '接收关于平台的技巧和更新',
      'Language & Region': '语言和地区',
      'Set your language and regional preferences': '设置您的语言和地区偏好',
      'Timezone': '时区',
      'Privacy & Security': '隐私和安全',
      'Manage your privacy settings and account security': '管理您的隐私设置和账户安全',
      'Profile Visibility': '个人资料可见性',
      'Make your profile visible to other users': '让其他用户可以看到您的个人资料',
      'Location Sharing': '位置共享',
      'Allow sharing your location during streams': '允许在直播时共享您的位置',
      'Change Password': '修改密码',
      'Delete Account': '删除账户',
      
      // Earnings page
      'Track your streaming revenue and performance': '跟踪您的直播收入和表现',
      'Total Earnings': '总收入',
      'All time': '总计',
      'This Month': '本月',
      '+12% from last month': '比上月增长12%',
      'Completed Streams': '已完成直播',
      'Average Rating': '平均评分',
      'From customer reviews': '来自客户评价',
      'Recent Earnings': '最近收入',
      'Your latest completed streaming sessions': '您最新完成的直播会话',
      
      // Streams page
      'Watch and manage your live streaming sessions': '观看和管理您的直播会话',
      'Live Now': '正在直播',
      'Watch Stream': '观看直播',
      'No Live Streams': '没有直播',
      'No streams are currently live. Check back later!': '目前没有直播。请稍后查看！',
      'Upcoming Streams': '即将开始的直播',
      'Scheduled': '已安排',
      'Set Reminder': '设置提醒',
      'No Upcoming Streams': '没有即将开始的直播',
      'No streams are scheduled yet.': '还没有安排直播。',
      'Times Square Night Walk': '时代广场夜游',
      'Exploring the bright lights of NYC': '探索纽约的璀璨灯光',
      'Times Square, NYC': '纽约时代广场',
      'Golden Gate Bridge View': '金门大桥景观',
      'Beautiful sunset view from Marin': '马林县美丽的日落景观',
      'San Francisco, CA': '加利福尼亚州旧金山',
      'Central Park Concert': '中央公园音乐会',
      'Live jazz performance in the park': '公园里的现场爵士乐表演'
    },
    'ja': {
      'Search by location or description...': '場所や説明で検索...',
      'All Categories': 'すべてのカテゴリ',
      'Any Price': '任意の価格',
      'Music': '音楽',
      'Food': '食べ物',
      'Travel': '旅行',
      'Events': 'イベント',
      'Fitness': 'フィットネス',
      'Education': '教育',
      'Available Orders': '利用可能な注文',
      'My Orders': 'マイオーダー',
      'Streaming Requests': 'ストリーミング要求',
      'Creator': 'クリエイター',
      'Price': '価格',
      'Total Pool': '総プール',
      'Accept Order': '注文を受け入れる',
      'Join Stream': 'ストリームに参加',
      'Open': 'オープン',
      'Completed': '完了',
      'Unavailable': '利用不可',
      'Pending': '保留中',
      'Accepted': '承認済み',
      'participants': '参加者',
      'min': '分',
      'Live Streams': 'ライブストリーム',
      'Discover': '発見',
      'Orders': '注文',
      'Streams': 'ストリーム',
      'Profile': 'プロフィール',
      'All': 'すべて',
      'Earnings': '収益',
      'Settings': '設定',
      'Content Creator': 'コンテンツクリエイター',
      'Discover Live Streams': 'ライブストリームを発見',
      'Find and create location-based streaming experiences': '位置ベースのストリーミング体験を見つけて作成',
      'API Connected': 'API接続済み',
      'API Disconnected': 'API切断中',
      'Active Streams Nearby': '近くのアクティブストリーム',
      'No active streams nearby at the moment': '現在近くにアクティブなストリームはありません',
      'No orders match your filters': 'フィルターに一致する注文がありません',
      'You haven\'t created any orders yet': 'まだ注文を作成していません',
      'Create Your First Order': '最初の注文を作成',
      'What would you like to stream?': '何をストリーミングしたいですか？',
      'Describe the streaming experience you want...': '希望するストリーミング体験を説明してください...',
      'Enter location (e.g., San Francisco, CA)': '場所を入力（例：東京、日本）',
      'Select duration': '時間を選択',
      'Select category': 'カテゴリを選択',
      'Get Current Location': '現在位置を取得',
      'Creating...': '作成中...',
      'Central Park Concert Stream': 'セントラルパークコンサートストリーム',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': '今夜セントラルパークで開催される野外コンサートをストリーミングしてくれる人を探しています',
      'Food Market Tour': 'フードマーケットツアー',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'パイクプレイスマーケットのガイドツアーをストリーミングして、地元の業者と食べ物を紹介してほしい',
      'Pike Place Market, Seattle': 'シアトル、パイクプレイスマーケット',
      'Beach Sunset Yoga': 'ビーチサンセットヨガ',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'ウェルネス愛好家のためにサンタモニカビーチで平和的な夕日ヨガセッションをストリーミング',
      'Santa Monica Beach, CA': 'カリフォルニア州、サンタモニカビーチ',
      'Success': '成功',
      'Error': 'エラー',
      'Connection Error': '接続エラー',
      'Failed to connect to the server': 'サーバーに接続できませんでした',
      'Order accepted successfully!': '注文が正常に承認されました！',
      'Failed to accept order': '注文の承認に失敗しました',
      'Joining Stream': 'ストリームに参加',
      'Opening live stream...': 'ライブストリームを開いています...',
      'Language / 语言': '言語 / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVPプラットフォーム',
      'Sarah Chen': 'サラ・チェン',
      'In 1h': '1時間後',
      'In 23h': '23時間後', 
      'In 2 days': '2日後',
      'No pending orders': '保留中の注文がありません',
      'No open orders': 'オープンな注文がありません',
      'No accepted orders': '承認された注文がありません',
      'No live streams': 'ライブストリームがありません',
      'No completed orders': '完了した注文がありません',
      
      // Settings page
      'Manage your account preferences and streaming settings': 'アカウント設定とストリーミング設定を管理',
      'Profile Settings': 'プロフィール設定',
      'Update your personal information and profile details': '個人情報とプロフィール詳細を更新',
      'First Name': '名前',
      'Last Name': '姓',
      'Email': 'メール',
      'Bio': '自己紹介',
      'Tell viewers about yourself...': '視聴者に自己紹介をしてください...',
      'Professional content creator specializing in travel and lifestyle streaming.': '旅行とライフスタイルストリーミングを専門とするプロのコンテンツクリエイター。',
      'Save Profile': 'プロフィールを保存',
      'Streaming Settings': 'ストリーミング設定',
      'Configure your default streaming preferences': 'デフォルトのストリーミング設定を構成',
      'Default Stream Duration': 'デフォルトストリーム時間',
      'Default Category': 'デフォルトカテゴリ',
      'Auto-start recording': '自動録画開始',
      'Automatically record all your streams': 'すべてのストリームを自動録画',
      'HD Quality': 'HD画質',
      'Stream in high definition (uses more data)': '高画質でストリーム（データ使用量が多い）',
      'Notifications': '通知',
      'Choose what notifications you want to receive': '受信したい通知を選択',
      'New Order Alerts': '新規注文アラート',
      'Get notified when someone places a new order': '新しい注文が入ったときに通知を受け取る',
      'Stream Reminders': 'ストリームリマインダー',
      'Remind you before scheduled streams': '予定されたストリーム前にリマインド',
      'Payment Notifications': '支払い通知',
      'Get notified when you receive payments': '支払いを受け取ったときに通知を受け取る',
      'Marketing Emails': 'マーケティングメール',
      'Receive tips and updates about the platform': 'プラットフォームのヒントと更新を受け取る',
      'Language & Region': '言語と地域',
      'Set your language and regional preferences': '言語と地域の設定',
      'Timezone': 'タイムゾーン',
      'Privacy & Security': 'プライバシーとセキュリティ',
      'Manage your privacy settings and account security': 'プライバシー設定とアカウントセキュリティを管理',
      'Profile Visibility': 'プロフィールの表示',
      'Make your profile visible to other users': '他のユーザーにプロフィールを表示',
      'Location Sharing': '位置情報の共有',
      'Allow sharing your location during streams': 'ストリーム中の位置情報共有を許可',
      'Change Password': 'パスワード変更',
      'Delete Account': 'アカウント削除',
      
      // Earnings page
      'Track your streaming revenue and performance': 'ストリーミング収益とパフォーマンスを追跡',
      'Total Earnings': '総収益',
      'All time': '全期間',
      'This Month': '今月',
      '+12% from last month': '先月より12%増',
      'Completed Streams': '完了したストリーム',
      'Average Rating': '平均評価',
      'From customer reviews': '顧客レビューから',
      'Recent Earnings': '最近の収益',
      'Your latest completed streaming sessions': '最新の完了したストリーミングセッション',
      
      // Streams page
      'Watch and manage your live streaming sessions': 'ライブストリーミングセッションを視聴・管理',
      'Live Now': 'ライブ中',
      'Watch Stream': 'ストリームを視聴',
      'No Live Streams': 'ライブストリームなし',
      'No streams are currently live. Check back later!': '現在ライブ中のストリームはありません。後でチェックしてください！',
      'Upcoming Streams': '今後のストリーム',
      'Scheduled': '予定済み',
      'Set Reminder': 'リマインダー設定',
      'No Upcoming Streams': '今後のストリームなし',
      'No streams are scheduled yet.': 'まだストリームが予定されていません。',
      'Times Square Night Walk': 'タイムズスクエア夜の散歩',
      'Exploring the bright lights of NYC': 'NYCの明るい光を探索',
      'Times Square, NYC': 'タイムズスクエア、NYC',
      'Golden Gate Bridge View': 'ゴールデンゲートブリッジビュー',
      'Beautiful sunset view from Marin': 'マリンからの美しい夕日の眺め',
      'San Francisco, CA': 'サンフランシスコ、CA',
      'Central Park Concert': 'セントラルパークコンサート',
      'Live jazz performance in the park': '公園でのライブジャズパフォーマンス'
    },
    'es': {
      'Search by location or description...': 'Buscar por ubicación o descripción...',
      'All Categories': 'Todas las categorías',
      'Any Price': 'Cualquier precio',
      'Music': 'Música',
      'Food': 'Comida',
      'Travel': 'Viaje',
      'Events': 'Eventos',
      'Fitness': 'Fitness',
      'Education': 'Educación',
      'Available Orders': 'Pedidos disponibles',
      'My Orders': 'Mis pedidos',
      'Streaming Requests': 'Solicitudes de transmisión',
      'Creator': 'Creador',
      'Price': 'Precio',
      'Total Pool': 'Pool total',
      'Accept Order': 'Aceptar pedido',
      'Join Stream': 'Unirse al stream',
      'Open': 'Abierto',
      'Live': 'En vivo',
      'Completed': 'Completado',
      'Unavailable': 'No disponible',
      'Pending': 'Pendiente',
      'Accepted': 'Aceptado',
      'participants': 'participantes',
      'min': 'min',
      'Create Order': 'Crear pedido',
      'Live Streams': 'Transmisiones en Vivo',
      'Discover': 'Descubrir',
      'Orders': 'Pedidos',
      'Streams': 'Transmisiones',
      'Profile': 'Perfil',
      'All': 'Todos',
      'Earnings': 'Ganancias',
      'Settings': 'Configuración',
      'Content Creator': 'Creador de Contenido',
      'Discover Live Streams': 'Descubrir Transmisiones en Vivo',
      'Find and create location-based streaming experiences': 'Encuentra y crea experiencias de transmisión basadas en ubicación',
      'API Connected': 'API Conectado',
      'API Disconnected': 'API Desconectado',
      'Active Streams Nearby': 'Transmisiones Activas Cercanas',
      'No active streams nearby at the moment': 'No hay transmisiones activas cerca en este momento',
      'No orders match your filters': 'Ningún pedido coincide con tus filtros',
      'You haven\'t created any orders yet': 'Aún no has creado ningún pedido',
      'Create Your First Order': 'Crear Tu Primer Pedido',
      'What would you like to stream?': '¿Qué te gustaría transmitir?',
      'Describe the streaming experience you want...': 'Describe la experiencia de transmisión que deseas...',
      'Enter location (e.g., San Francisco, CA)': 'Ingresa ubicación (ej: Madrid, España)',
      'Select duration': 'Seleccionar duración',
      'Select category': 'Seleccionar categoría',
      'Get Current Location': 'Obtener Ubicación Actual',
      'Creating...': 'Creando...',
      'Central Park Concert Stream': 'Stream de Concierto en Central Park',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'Buscando a alguien para transmitir el concierto al aire libre que ocurre en Central Park esta noche',
      'Central Park, NYC': 'Central Park, Nueva York',
      'Food Market Tour': 'Tour del Mercado de Comida',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'Quiero que alguien transmita un tour guiado del Mercado Pike Place, mostrando vendedores locales y comida',
      'Pike Place Market, Seattle': 'Mercado Pike Place, Seattle',
      'Beach Sunset Yoga': 'Yoga de Atardecer en la Playa',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'Transmitir una sesión pacífica de yoga al atardecer en la Playa Santa Monica para entusiastas del bienestar',
      'Santa Monica Beach, CA': 'Playa Santa Monica, California',
      'Success': 'Éxito',
      'Error': 'Error',
      'Connection Error': 'Error de Conexión',
      'Failed to connect to the server': 'Error al conectar con el servidor',
      'Order accepted successfully!': '¡Pedido aceptado exitosamente!',
      'Failed to accept order': 'Error al aceptar pedido',
      'Joining Stream': 'Unirse al Stream',
      'Opening live stream...': 'Abriendo transmisión en vivo...',
      'Language / 语言': 'Idioma / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'Plataforma MVP',
      'Sarah Chen': 'Sarah Chen',
      'In 1h': 'En 1h',
      'In 23h': 'En 23h',
      'In 2 days': 'En 2 días',
      'No pending orders': 'No hay pedidos pendientes',
      'No open orders': 'No hay pedidos abiertos',
      'No accepted orders': 'No hay pedidos aceptados',
      'No live streams': 'No hay transmisiones en vivo',
      'No completed orders': 'No hay pedidos completados',
      
      // Settings page
      'Manage your account preferences and streaming settings': 'Administra las preferencias de tu cuenta y configuración de transmisión',
      'Profile Settings': 'Configuración de Perfil',
      'Update your personal information and profile details': 'Actualiza tu información personal y detalles del perfil',
      'First Name': 'Nombre',
      'Last Name': 'Apellido',
      'Email': 'Correo electrónico',
      'Bio': 'Biografía',
      'Tell viewers about yourself...': 'Cuéntales a los espectadores sobre ti...',
      'Professional content creator specializing in travel and lifestyle streaming.': 'Creador de contenido profesional especializado en transmisión de viajes y estilo de vida.',
      'Save Profile': 'Guardar Perfil',
      'Streaming Settings': 'Configuración de Transmisión',
      'Configure your default streaming preferences': 'Configura tus preferencias predeterminadas de transmisión',
      'Default Stream Duration': 'Duración Predeterminada de Transmisión',
      'Default Category': 'Categoría Predeterminada',
      'Auto-start recording': 'Iniciar grabación automáticamente',
      'Automatically record all your streams': 'Graba automáticamente todas tus transmisiones',
      'HD Quality': 'Calidad HD',
      'Stream in high definition (uses more data)': 'Transmite en alta definición (usa más datos)',
      'Notifications': 'Notificaciones',
      'Choose what notifications you want to receive': 'Elige qué notificaciones quieres recibir',
      'New Order Alerts': 'Alertas de Nuevos Pedidos',
      'Get notified when someone places a new order': 'Recibe notificaciones cuando alguien haga un nuevo pedido',
      'Stream Reminders': 'Recordatorios de Transmisión',
      'Remind you before scheduled streams': 'Te recuerda antes de transmisiones programadas',
      'Payment Notifications': 'Notificaciones de Pago',
      'Get notified when you receive payments': 'Recibe notificaciones cuando recibas pagos',
      'Marketing Emails': 'Correos de Marketing',
      'Receive tips and updates about the platform': 'Recibe consejos y actualizaciones sobre la plataforma',
      'Language & Region': 'Idioma y Región',
      'Set your language and regional preferences': 'Establece tu idioma y preferencias regionales',
      'Timezone': 'Zona Horaria',
      'Privacy & Security': 'Privacidad y Seguridad',
      'Manage your privacy settings and account security': 'Administra tu configuración de privacidad y seguridad de cuenta',
      'Profile Visibility': 'Visibilidad del Perfil',
      'Make your profile visible to other users': 'Haz que tu perfil sea visible para otros usuarios',
      'Location Sharing': 'Compartir Ubicación',
      'Allow sharing your location during streams': 'Permite compartir tu ubicación durante transmisiones',
      'Change Password': 'Cambiar Contraseña',
      'Delete Account': 'Eliminar Cuenta',
      
      // Earnings page
      'Track your streaming revenue and performance': 'Rastrea tus ingresos y rendimiento de transmisión',
      'Total Earnings': 'Ganancias Totales',
      'All time': 'Todos los tiempos',
      'This Month': 'Este Mes',
      '+12% from last month': '+12% desde el mes pasado',
      'Completed Streams': 'Transmisiones Completadas',
      'Average Rating': 'Calificación Promedio',
      'From customer reviews': 'De reseñas de clientes',
      'Recent Earnings': 'Ganancias Recientes',
      'Your latest completed streaming sessions': 'Tus últimas sesiones de transmisión completadas',
      
      // Streams page
      'Watch and manage your live streaming sessions': 'Ve y administra tus sesiones de transmisión en vivo',
      'Live Now': 'En Vivo Ahora',
      'Watch Stream': 'Ver Transmisión',
      'No Live Streams': 'No Hay Transmisiones en Vivo',
      'No streams are currently live. Check back later!': 'No hay transmisiones en vivo actualmente. ¡Vuelve más tarde!',
      'Upcoming Streams': 'Próximas Transmisiones',
      'Scheduled': 'Programado',
      'Set Reminder': 'Establecer Recordatorio',
      'No Upcoming Streams': 'No Hay Próximas Transmisiones',
      'No streams are scheduled yet.': 'Aún no hay transmisiones programadas.',
      'Times Square Night Walk': 'Caminata Nocturna por Times Square',
      'Exploring the bright lights of NYC': 'Explorando las luces brillantes de NYC',
      'Times Square, NYC': 'Times Square, NYC',
      'Golden Gate Bridge View': 'Vista del Puente Golden Gate',
      'Beautiful sunset view from Marin': 'Hermosa vista del atardecer desde Marin',
      'San Francisco, CA': 'San Francisco, CA',
      'Central Park Concert': 'Concierto en Central Park',
      'Live jazz performance in the park': 'Actuación de jazz en vivo en el parque'
    },
    'ko': {
      'Search by location or description...': '위치 또는 설명으로 검색...',
      'All Categories': '모든 카테고리',
      'Any Price': '모든 가격',
      'Music': '음악',
      'Food': '음식',
      'Travel': '여행',
      'Events': '이벤트',
      'Fitness': '피트니스',
      'Education': '교육',
      'Available Orders': '이용 가능한 주문',
      'My Orders': '내 주문',
      'Streaming Requests': '스트리밍 요청',
      'Creator': '크리에이터',
      'Price': '가격',
      'Total Pool': '총 풀',
      'Accept Order': '주문 수락',
      'Join Stream': '스트림 참여',
      'Completed': '완료됨',
      'Unavailable': '이용 불가',
      'Open': '열림',
      'Pending': '대기 중',
      'Live': '라이브',
      'Accepted': '수락됨',
      'participants': '참가자',
      'min': '분',
      'Create Order': '주문 생성',
      'Discover': '발견',
      'Earnings': '수익',
      'Settings': '설정',
      'Content Creator': '콘텐츠 크리에이터',
      'Live Streams': '라이브 스트림',
      'Orders': '주문',
      'Streams': '스트림',
      'Profile': '프로필',
      'All': '모든',
      'Discover Live Streams': '라이브 스트림 발견',
      'Find and create location-based streaming experiences': '위치 기반 스트리밍 경험을 찾고 만드세요',
      'API Connected': 'API 연결됨',
      'API Disconnected': 'API 연결 끊김',
      'Active Streams Nearby': '근처 활성 스트림',
      'No active streams nearby at the moment': '현재 근처에 활성 스트림이 없습니다',
      'No orders match your filters': '필터와 일치하는 주문이 없습니다',
      'You haven\'t created any orders yet': '아직 주문을 생성하지 않았습니다',
      'Create Your First Order': '첫 번째 주문 생성',
      'What would you like to stream?': '무엇을 스트리밍하고 싶나요?',
      'Describe the streaming experience you want...': '원하는 스트리밍 경험을 설명하세요...',
      'Enter location (e.g., San Francisco, CA)': '위치 입력 (예: 서울, 한국)',
      'Select duration': '지속 시간 선택',
      'Select category': '카테고리 선택',
      'Get Current Location': '현재 위치 가져오기',
      'Creating...': '생성 중...',
      'Central Park Concert Stream': '센트럴 파크 콘서트 스트림',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': '오늘 저녁 센트럴 파크에서 열리는 야외 콘서트를 스트리밍할 사람을 찾고 있습니다',
      'Central Park, NYC': '뉴욕 센트럴 파크',
      'Food Market Tour': '음식 시장 투어',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': '파이크 플레이스 마켓의 가이드 투어를 스트리밍하여 현지 상인과 음식을 보여줄 사람을 원합니다',
      'Pike Place Market, Seattle': '시애틀 파이크 플레이스 마켓',
      'Beach Sunset Yoga': '해변 일몰 요가',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': '웰니스 애호가들을 위해 산타모니카 해변에서 평화로운 일몰 요가 세션을 스트리밍',
      'Santa Monica Beach, CA': '캘리포니아 산타모니카 해변',
      'Success': '성공',
      'Error': '오류',
      'Connection Error': '연결 오류',
      'Failed to connect to the server': '서버에 연결할 수 없습니다',
      'Order accepted successfully!': '주문이 성공적으로 승인되었습니다!',
      'Failed to accept order': '주문 승인 실패',
      'Joining Stream': '스트림 참여',
      'Opening live stream...': '라이브 스트림 열기...',
      'Language / 语言': '언어 / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVP 플랫폼',
      'Sarah Chen': '사라 첸',
      'In 1h': '1시간 후',
      'In 23h': '23시간 후',
      'In 2 days': '2일 후',
      'No pending orders': '대기 중인 주문이 없습니다',
      'No open orders': '열린 주문이 없습니다',
      'No accepted orders': '수락된 주문이 없습니다',
      'No live streams': '라이브 스트림이 없습니다',
      'No completed orders': '완료된 주문이 없습니다',
      
      // Settings page
      'Manage your account preferences and streaming settings': '계정 설정 및 스트리밍 설정 관리',
      'Profile Settings': '프로필 설정',
      'Update your personal information and profile details': '개인 정보 및 프로필 세부 정보 업데이트',
      'First Name': '이름',
      'Last Name': '성',
      'Email': '이메일',
      'Bio': '자기소개',
      'Tell viewers about yourself...': '시청자들에게 자신을 소개해보세요...',
      'Professional content creator specializing in travel and lifestyle streaming.': '여행과 라이프스타일 스트리밍을 전문으로 하는 프로 콘텐츠 크리에이터입니다.',
      'Save Profile': '프로필 저장',
      'Streaming Settings': '스트리밍 설정',
      'Configure your default streaming preferences': '기본 스트리밍 설정 구성',
      'Default Stream Duration': '기본 스트림 시간',
      'Default Category': '기본 카테고리',
      'Auto-start recording': '자동 녹화 시작',
      'Automatically record all your streams': '모든 스트림을 자동으로 녹화',
      'HD Quality': 'HD 화질',
      'Stream in high definition (uses more data)': '고화질로 스트리밍 (더 많은 데이터 사용)',
      'Notifications': '알림',
      'Choose what notifications you want to receive': '받고 싶은 알림을 선택하세요',
      'New Order Alerts': '새 주문 알림',
      'Get notified when someone places a new order': '누군가 새 주문을 할 때 알림 받기',
      'Stream Reminders': '스트림 알림',
      'Remind you before scheduled streams': '예정된 스트림 전에 알림',
      'Payment Notifications': '결제 알림',
      'Get notified when you receive payments': '결제를 받을 때 알림 받기',
      'Marketing Emails': '마케팅 이메일',
      'Receive tips and updates about the platform': '플랫폼에 대한 팁과 업데이트 받기',
      'Language & Region': '언어 및 지역',
      'Set your language and regional preferences': '언어 및 지역 설정을 구성하세요',
      'Timezone': '시간대',
      'Privacy & Security': '개인정보 보호 및 보안',
      'Manage your privacy settings and account security': '개인정보 설정 및 계정 보안 관리',
      'Profile Visibility': '프로필 공개',
      'Make your profile visible to other users': '다른 사용자에게 프로필 공개',
      'Location Sharing': '위치 공유',
      'Allow sharing your location during streams': '스트리밍 중 위치 공유 허용',
      'Change Password': '비밀번호 변경',
      'Delete Account': '계정 삭제',
      
      // Time zones
      'America/New_York': '미국/뉴욕',
      'America/Chicago': '미국/시카고',
      'America/Denver': '미국/덴버',
      'America/Los_Angeles': '미국/로스앤젤레스',
      'Europe/London': '유럽/런던',
      'Europe/Paris': '유럽/파리',
      'Asia/Tokyo': '아시아/도쿄',
      'Asia/Seoul': '아시아/서울',
      'Pacific Standard Time (PST)': '태평양 표준시 (PST)',
      'Mountain Standard Time (MST)': '산지 표준시 (MST)',
      'Central Standard Time (CST)': '중부 표준시 (CST)',
      'Eastern Standard Time (EST)': '동부 표준시 (EST)',
      'Coordinated Universal Time (UTC)': '협정 세계시 (UTC)',
      
      // Earnings page
      'Track your streaming revenue and performance': '스트리밍 수익 및 성과 추적',
      'Total Earnings': '총 수익',
      'All time': '전체 기간',
      'This Month': '이번 달',
      '+12% from last month': '지난달 대비 +12%',
      'Completed Streams': '완료된 스트림',
      'Average Rating': '평균 평점',
      'From customer reviews': '고객 리뷰에서',
      'Recent Earnings': '최근 수익',
      'Your latest completed streaming sessions': '최근 완료된 스트리밍 세션',
      
      // Streams page
      'Watch and manage your live streaming sessions': '라이브 스트리밍 세션 시청 및 관리',
      'Live Now': '현재 라이브',
      'Watch Stream': '스트림 시청',
      'No Live Streams': '라이브 스트림 없음',
      'No streams are currently live. Check back later!': '현재 라이브 중인 스트림이 없습니다. 나중에 다시 확인해주세요!',
      'Upcoming Streams': '예정된 스트림',
      'Scheduled': '예정됨',
      'Set Reminder': '알림 설정',
      'No Upcoming Streams': '예정된 스트림 없음',
      'No streams are scheduled yet.': '아직 예정된 스트림이 없습니다.',
      'Times Square Night Walk': '타임스퀘어 야간 산책',
      'Exploring the bright lights of NYC': 'NYC의 밝은 불빛 탐험',
      'Times Square, NYC': '타임스퀘어, NYC',
      'Golden Gate Bridge View': '골든 게이트 브리지 뷰',
      'Beautiful sunset view from Marin': '마린에서 보는 아름다운 일몰',
      'San Francisco, CA': '샌프란시스코, CA',
      'Central Park Concert': '센트럴 파크 콘서트',
      'Live jazz performance in the park': '공원에서의 라이브 재즈 공연'
    },
    'fr': {
      'Search by location or description...': 'Rechercher par lieu ou description...',
      'All Categories': 'Toutes les catégories',
      'Any Price': 'Tous les prix',
      'Music': 'Musique',
      'Food': 'Nourriture',
      'Travel': 'Voyage',
      'Events': 'Événements',
      'Fitness': 'Fitness',
      'Education': 'Éducation',
      'Available Orders': 'Commandes disponibles',
      'My Orders': 'Mes commandes',
      'Streaming Requests': 'Demandes de streaming',
      'Creator': 'Créateur',
      'Price': 'Prix',
      'Total Pool': 'Pool total',
      'Accept Order': 'Accepter la commande',
      'Join Stream': 'Rejoindre le stream',
      'Completed': 'Terminé',
      'Unavailable': 'Indisponible',
      'Open': 'Ouvert',
      'Pending': 'En attente',
      'Live': 'En direct',
      'Accepted': 'Accepté',
      'participants': 'participants',
      'min': 'min',
      'Create Order': 'Créer une commande',
      'Discover': 'Découvrir',
      'Earnings': 'Revenus',
      'Settings': 'Paramètres',
      'Content Creator': 'Créateur de contenu',
      'Live Streams': 'Streams en direct',
      'Orders': 'Commandes',
      'Streams': 'Streams',
      'Profile': 'Profil',
      'All': 'Tous',
      'Discover Live Streams': 'Découvrir les streams en direct',
      'Find and create location-based streaming experiences': 'Trouvez et créez des expériences de streaming basées sur la localisation',
      'API Connected': 'API connectée',
      'API Disconnected': 'API déconnectée',
      'Active Streams Nearby': 'Streams actifs à proximité',
      'No active streams nearby at the moment': 'Aucun stream actif à proximité pour le moment',
      'No orders match your filters': 'Aucune commande ne correspond à vos filtres',
      'You haven\'t created any orders yet': 'Vous n\'avez pas encore créé de commandes',
      'Create Your First Order': 'Créer votre première commande',
      'What would you like to stream?': 'Que souhaitez-vous streamer ?',
      'Describe the streaming experience you want...': 'Décrivez l\'expérience de streaming que vous voulez...',
      'Enter location (e.g., San Francisco, CA)': 'Entrez l\'emplacement (ex: Paris, France)',
      'Select duration': 'Sélectionner la durée',
      'Select category': 'Sélectionner la catégorie',
      'Get Current Location': 'Obtenir la position actuelle',
      'Creating...': 'Création...',
      'Central Park Concert Stream': 'Stream Concert Central Park',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'Recherche quelqu\'un pour streamer le concert en plein air qui se déroule à Central Park ce soir',
      'Central Park, NYC': 'Central Park, New York',
      'Food Market Tour': 'Tour du Marché Alimentaire',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'Je veux que quelqu\'un stream une visite guidée du Pike Place Market, présentant les vendeurs locaux et la nourriture',
      'Pike Place Market, Seattle': 'Pike Place Market, Seattle',
      'Beach Sunset Yoga': 'Yoga Coucher de Soleil sur la Plage',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'Streamez une session de yoga paisible au coucher du soleil à Santa Monica Beach pour les passionnés de bien-être',
      'Santa Monica Beach, CA': 'Plage de Santa Monica, Californie',
      'Language / 语言': 'Langue / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'Plateforme MVP',
      'Sarah Chen': 'Sarah Chen',
      'In 1h': 'Dans 1h',
      'In 23h': 'Dans 23h',
      'In 2 days': 'Dans 2 jours',
      'No pending orders': 'Aucune commande en attente',
      'No open orders': 'Aucune commande ouverte',
      'No accepted orders': 'Aucune commande acceptée',
      'No live streams': 'Aucun stream en direct',
      'No completed orders': 'Aucune commande terminée',
      
      // Settings page
      'Manage your account preferences and streaming settings': 'Gérez vos préférences de compte et paramètres de streaming',
      'Profile Settings': 'Paramètres de Profil',
      'Update your personal information and profile details': 'Mettez à jour vos informations personnelles et détails de profil',
      'First Name': 'Prénom',
      'Last Name': 'Nom',
      'Email': 'Email',
      'Bio': 'Biographie',
      'Tell viewers about yourself...': 'Parlez de vous aux spectateurs...',
      'Professional content creator specializing in travel and lifestyle streaming.': 'Créateur de contenu professionnel spécialisé dans le streaming de voyage et de style de vie.',
      'Save Profile': 'Sauvegarder le Profil',
      'Streaming Settings': 'Paramètres de Streaming',
      'Configure your default streaming preferences': 'Configurez vos préférences de streaming par défaut',
      'Default Stream Duration': 'Durée de Stream par Défaut',
      'Default Category': 'Catégorie par Défaut',
      'Auto-start recording': 'Démarrage automatique de l\'enregistrement',
      'Automatically record all your streams': 'Enregistrez automatiquement tous vos streams',
      'HD Quality': 'Qualité HD',
      'Stream in high definition (uses more data)': 'Streamez en haute définition (utilise plus de données)',
      'Notifications': 'Notifications',
      'Choose what notifications you want to receive': 'Choisissez les notifications que vous souhaitez recevoir',
      'New Order Alerts': 'Alertes Nouvelles Commandes',
      'Get notified when someone places a new order': 'Soyez notifié lorsque quelqu\'un passe une nouvelle commande',
      'Stream Reminders': 'Rappels de Stream',
      'Remind you before scheduled streams': 'Vous rappelle avant les streams programmés',
      'Payment Notifications': 'Notifications de Paiement',
      'Get notified when you receive payments': 'Soyez notifié lorsque vous recevez des paiements',
      'Marketing Emails': 'Emails Marketing',
      'Receive tips and updates about the platform': 'Recevez des conseils et mises à jour sur la plateforme',
      'Language & Region': 'Langue et Région',
      'Set your language and regional preferences': 'Définissez vos préférences de langue et région',
      'Timezone': 'Fuseau Horaire',
      'Privacy & Security': 'Confidentialité et Sécurité',
      'Manage your privacy settings and account security': 'Gérez vos paramètres de confidentialité et sécurité du compte',
      'Profile Visibility': 'Visibilité du Profil',
      'Make your profile visible to other users': 'Rendez votre profil visible aux autres utilisateurs',
      'Location Sharing': 'Partage de Localisation',
      'Allow sharing your location during streams': 'Autorisez le partage de votre localisation pendant les streams',
      'Change Password': 'Changer le Mot de Passe',
      'Delete Account': 'Supprimer le Compte',
      
      // Time zones
      'America/New_York': 'Amérique/New York',
      'America/Chicago': 'Amérique/Chicago',
      'America/Denver': 'Amérique/Denver',
      'America/Los_Angeles': 'Amérique/Los Angeles',
      'Europe/London': 'Europe/Londres',
      'Europe/Paris': 'Europe/Paris',
      'Asia/Tokyo': 'Asie/Tokyo',
      'Asia/Seoul': 'Asie/Séoul',
      'Pacific Standard Time (PST)': 'Heure Standard du Pacifique (PST)',
      'Mountain Standard Time (MST)': 'Heure Standard des Montagnes (MST)',
      'Central Standard Time (CST)': 'Heure Standard du Centre (CST)',
      'Eastern Standard Time (EST)': 'Heure Standard de l\'Est (EST)',
      'Coordinated Universal Time (UTC)': 'Temps Universel Coordonné (UTC)',
      
      // Earnings page
      'Track your streaming revenue and performance': 'Suivez vos revenus et performances de streaming',
      'Total Earnings': 'Revenus Totaux',
      'All time': 'Depuis toujours',
      'This Month': 'Ce Mois',
      '+12% from last month': '+12% par rapport au mois dernier',
      'Completed Streams': 'Streams Terminés',
      'Average Rating': 'Note Moyenne',
      'From customer reviews': 'D\'après les avis clients',
      'Recent Earnings': 'Revenus Récents',
      'Your latest completed streaming sessions': 'Vos dernières sessions de streaming terminées',
      
      // Streams page
      'Watch and manage your live streaming sessions': 'Regardez et gérez vos sessions de streaming en direct',
      'Live Now': 'En Direct Maintenant',
      'Watch Stream': 'Regarder le Stream',
      'No Live Streams': 'Aucun Stream en Direct',
      'No streams are currently live. Check back later!': 'Aucun stream n\'est actuellement en direct. Revenez plus tard !',
      'Upcoming Streams': 'Streams Prochains',
      'Scheduled': 'Programmé',
      'Set Reminder': 'Définir un Rappel',
      'No Upcoming Streams': 'Aucun Stream Prochain',
      'No streams are scheduled yet.': 'Aucun stream n\'est encore programmé.',
      'Times Square Night Walk': 'Promenade Nocturne à Times Square',
      'Exploring the bright lights of NYC': 'Exploration des lumières brillantes de NYC',
      'Times Square, NYC': 'Times Square, NYC',
      'Golden Gate Bridge View': 'Vue du Golden Gate Bridge',
      'Beautiful sunset view from Marin': 'Belle vue du coucher de soleil depuis Marin',
      'San Francisco, CA': 'San Francisco, CA',
      'Central Park Concert': 'Concert de Central Park',
      'Live jazz performance in the park': 'Performance de jazz en direct dans le parc'
    },
    'de': {
      'Search by location or description...': 'Nach Ort oder Beschreibung suchen...',
      'All Categories': 'Alle Kategorien',
      'Any Price': 'Jeder Preis',
      'Music': 'Musik',
      'Food': 'Essen',
      'Travel': 'Reisen',
      'Events': 'Veranstaltungen',
      'Fitness': 'Fitness',
      'Education': 'Bildung',
      'Available Orders': 'Verfügbare Bestellungen',
      'My Orders': 'Meine Bestellungen',
      'Streaming Requests': 'Streaming-Anfragen',
      'Creator': 'Ersteller',
      'Price': 'Preis',
      'Total Pool': 'Gesamtpool',
      'Accept Order': 'Bestellung annehmen',
      'Join Stream': 'Stream beitreten',
      'Completed': 'Abgeschlossen',
      'Unavailable': 'Nicht verfügbar',
      'Open': 'Offen',
      'Pending': 'Ausstehend',
      'Live': 'Live',
      'Accepted': 'Angenommen',
      'participants': 'Teilnehmer',
      'min': 'Min',
      'Create Order': 'Bestellung erstellen',
      'Discover': 'Entdecken',
      'Orders': 'Bestellungen',
      'Streams': 'Streams',
      'Profile': 'Profil',
      'All': 'Alle',
      'Live Streams': 'Live-Streams',
      'Earnings': 'Einnahmen',
      'Settings': 'Einstellungen',
      'Content Creator': 'Content-Ersteller',
      'Central Park Concert Stream': 'Central Park Konzert Stream',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'Suche jemanden, der das Outdoor-Konzert im Central Park heute Abend streamt',
      'Central Park, NYC': 'Central Park, New York',
      'Food Market Tour': 'Lebensmittelmarkt-Tour',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'Möchte, dass jemand eine geführte Tour durch den Pike Place Market streamt, mit lokalen Händlern und Essen',
      'Pike Place Market, Seattle': 'Pike Place Market, Seattle',
      'Beach Sunset Yoga': 'Strand Sonnenuntergang Yoga',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'Streame eine friedliche Sonnenuntergang-Yoga-Session am Santa Monica Beach für Wellness-Enthusiasten',
      'Santa Monica Beach, CA': 'Santa Monica Beach, Kalifornien',
      'Language / 语言': 'Sprache / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVP-Plattform',
      'Sarah Chen': 'Sarah Chen',
      'In 1h': 'In 1 Std',
      'In 23h': 'In 23 Std',
      'In 2 days': 'In 2 Tagen',
      'No pending orders': 'Keine ausstehenden Bestellungen',
      'No open orders': 'Keine offenen Bestellungen',
      'No accepted orders': 'Keine angenommenen Bestellungen',
      'No live streams': 'Keine Live-Streams',
      'No completed orders': 'Keine abgeschlossenen Bestellungen',
      
      // Settings page
      'Manage your account preferences and streaming settings': 'Verwalten Sie Ihre Kontoeinstellungen und Streaming-Einstellungen',
      'Profile Settings': 'Profil-Einstellungen',
      'Update your personal information and profile details': 'Aktualisieren Sie Ihre persönlichen Informationen und Profil-Details',
      'First Name': 'Vorname',
      'Last Name': 'Nachname',
      'Email': 'E-Mail',
      'Bio': 'Biografie',
      'Tell viewers about yourself...': 'Erzählen Sie den Zuschauern von sich...',
      'Professional content creator specializing in travel and lifestyle streaming.': 'Professioneller Content-Creator, spezialisiert auf Reise- und Lifestyle-Streaming.',
      'Save Profile': 'Profil Speichern',
      'Streaming Settings': 'Streaming-Einstellungen',
      'Configure your default streaming preferences': 'Konfigurieren Sie Ihre Standard-Streaming-Einstellungen',
      'Default Stream Duration': 'Standard Stream-Dauer',
      'Default Category': 'Standard-Kategorie',
      'Auto-start recording': 'Aufnahme automatisch starten',
      'Automatically record all your streams': 'Alle Ihre Streams automatisch aufzeichnen',
      'HD Quality': 'HD-Qualität',
      'Stream in high definition (uses more data)': 'In hoher Auflösung streamen (verbraucht mehr Daten)',
      'Notifications': 'Benachrichtigungen',
      'Choose what notifications you want to receive': 'Wählen Sie aus, welche Benachrichtigungen Sie erhalten möchten',
      'New Order Alerts': 'Neue Bestellungsbenachrichtigungen',
      'Get notified when someone places a new order': 'Benachrichtigung erhalten, wenn jemand eine neue Bestellung aufgibt',
      'Stream Reminders': 'Stream-Erinnerungen',
      'Remind you before scheduled streams': 'Erinnerung vor geplanten Streams',
      'Payment Notifications': 'Zahlungsbenachrichtigungen',
      'Get notified when you receive payments': 'Benachrichtigung erhalten, wenn Sie Zahlungen erhalten',
      'Marketing Emails': 'Marketing-E-Mails',
      'Receive tips and updates about the platform': 'Tipps und Updates über die Plattform erhalten',
      'Language & Region': 'Sprache & Region',
      'Set your language and regional preferences': 'Stellen Sie Ihre Sprach- und Regionspräferenzen ein',
      'Timezone': 'Zeitzone',
      'Privacy & Security': 'Datenschutz & Sicherheit',
      'Manage your privacy settings and account security': 'Verwalten Sie Ihre Datenschutzeinstellungen und Kontosicherheit',
      'Profile Visibility': 'Profil-Sichtbarkeit',
      'Make your profile visible to other users': 'Machen Sie Ihr Profil für andere Nutzer sichtbar',
      'Location Sharing': 'Standort-Freigabe',
      'Allow sharing your location during streams': 'Standort-Freigabe während Streams erlauben',
      'Change Password': 'Passwort Ändern',
      'Delete Account': 'Konto Löschen',
      
      // Time zones
      'America/New_York': 'Amerika/New York',
      'America/Chicago': 'Amerika/Chicago',
      'America/Denver': 'Amerika/Denver',
      'America/Los_Angeles': 'Amerika/Los Angeles',
      'Europe/London': 'Europa/London',
      'Europe/Paris': 'Europa/Paris',
      'Asia/Tokyo': 'Asien/Tokio',
      'Asia/Seoul': 'Asien/Seoul',
      'Pacific Standard Time (PST)': 'Pazifische Standardzeit (PST)',
      'Mountain Standard Time (MST)': 'Gebirgs-Standardzeit (MST)',
      'Central Standard Time (CST)': 'Zentrale Standardzeit (CST)',
      'Eastern Standard Time (EST)': 'Östliche Standardzeit (EST)',
      'Coordinated Universal Time (UTC)': 'Koordinierte Weltzeit (UTC)',
      
      // Earnings page
      'Track your streaming revenue and performance': 'Verfolgen Sie Ihre Streaming-Einnahmen und -Leistung',
      'Total Earnings': 'Gesamteinnahmen',
      'All time': 'Gesamtzeit',
      'This Month': 'Diesen Monat',
      '+12% from last month': '+12% gegenüber dem letzten Monat',
      'Completed Streams': 'Abgeschlossene Streams',
      'Average Rating': 'Durchschnittliche Bewertung',
      'From customer reviews': 'Aus Kundenbewertungen',
      'Recent Earnings': 'Aktuelle Einnahmen',
      'Your latest completed streaming sessions': 'Ihre letzten abgeschlossenen Streaming-Sitzungen',
      
      // Streams page
      'Watch and manage your live streaming sessions': 'Schauen und verwalten Sie Ihre Live-Streaming-Sitzungen',
      'Live Now': 'Jetzt Live',
      'Watch Stream': 'Stream Ansehen',
      'No Live Streams': 'Keine Live-Streams',
      'No streams are currently live. Check back later!': 'Derzeit sind keine Streams live. Schauen Sie später wieder vorbei!',
      'Upcoming Streams': 'Kommende Streams',
      'Scheduled': 'Geplant',
      'Set Reminder': 'Erinnerung Setzen',
      'No Upcoming Streams': 'Keine Kommenden Streams',
      'No streams are scheduled yet.': 'Es sind noch keine Streams geplant.',
      'Times Square Night Walk': 'Times Square Nachtspaziergang',
      'Exploring the bright lights of NYC': 'Die hellen Lichter von NYC erkunden',
      'Times Square, NYC': 'Times Square, NYC',
      'Golden Gate Bridge View': 'Golden Gate Bridge Aussicht',
      'Beautiful sunset view from Marin': 'Schöne Sonnenuntergangsaussicht von Marin',
      'San Francisco, CA': 'San Francisco, CA',
      'Central Park Concert': 'Central Park Konzert',
      'Live jazz performance in the park': 'Live Jazz-Performance im Park'
    },
    'ru': {
      'Search by location or description...': 'Поиск по местоположению или описанию...',
      'All Categories': 'Все категории',
      'Any Price': 'Любая цена',
      'Music': 'Музыка',
      'Food': 'Еда',
      'Travel': 'Путешествия',
      'Events': 'События',
      'Fitness': 'Фитнес',
      'Education': 'Образование',
      'Available Orders': 'Доступные заказы',
      'My Orders': 'Мои заказы',
      'Streaming Requests': 'Запросы на стриминг',
      'Creator': 'Создатель',
      'Price': 'Цена',
      'Total Pool': 'Общий пул',
      'Accept Order': 'Принять заказ',
      'Join Stream': 'Присоединиться к стриму',
      'Completed': 'Завершено',
      'Unavailable': 'Недоступно',
      'Open': 'Открыт',
      'Pending': 'Ожидание',
      'Live': 'В эфире',
      'Accepted': 'Принято',
      'participants': 'участники',
      'min': 'мин',
      'Create Order': 'Создать заказ',
      'Discover': 'Обнаружить',
      'Orders': 'Заказы',
      'Streams': 'Стримы',
      'Profile': 'Профиль',
      'All': 'Все',
      'Live Streams': 'Прямые трансляции',
      'Earnings': 'Доходы',
      'Settings': 'Настройки',
      'Content Creator': 'Создатель контента',
      'Central Park Concert Stream': 'Стрим концерта в Центральном парке',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'Ищу кого-то для трансляции концерта под открытым небом в Центральном парке сегодня вечером',
      'Central Park, NYC': 'Центральный парк, Нью-Йорк',
      'Food Market Tour': 'Тур по продуктовому рынку',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'Хочу, чтобы кто-то транслировал экскурсию по рынку Пайк-Плейс, показывая местных продавцов и еду',
      'Pike Place Market, Seattle': 'Рынок Пайк-Плейс, Сиэтл',
      'Beach Sunset Yoga': 'Йога на закате на пляже',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'Транслируйте спокойную сессию йоги на закате на пляже Санта-Моника для любителей wellness',
      'Santa Monica Beach, CA': 'Пляж Санта-Моника, Калифорния',
      'Language / 语言': 'Язык / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVP Платформа',
      'Sarah Chen': 'Сара Чен',
      'In 1h': 'Через 1 ч',
      'In 23h': 'Через 23 ч',
      'In 2 days': 'Через 2 дня',
      'No pending orders': 'Нет заказов в ожидании',
      'No open orders': 'Нет открытых заказов',
      'No accepted orders': 'Нет принятых заказов',
      'No live streams': 'Нет прямых трансляций',
      'No completed orders': 'Нет завершенных заказов'
    },
    'pt': {
      'Search by location or description...': 'Pesquisar por localização ou descrição...',
      'All Categories': 'Todas as categorias',
      'Any Price': 'Qualquer preço',
      'Music': 'Música',
      'Food': 'Comida',
      'Travel': 'Viagem',
      'Events': 'Eventos',
      'Fitness': 'Fitness',
      'Education': 'Educação',
      'Available Orders': 'Pedidos disponíveis',
      'My Orders': 'Meus pedidos',
      'Streaming Requests': 'Solicitações de streaming',
      'Creator': 'Criador',
      'Price': 'Preço',
      'Total Pool': 'Pool total',
      'Accept Order': 'Aceitar pedido',
      'Join Stream': 'Participar do stream',
      'Open': 'Aberto',
      'Live': 'Ao vivo',
      'Completed': 'Completado',
      'Unavailable': 'Indisponível',
      'Pending': 'Pendente',
      'Accepted': 'Aceito',
      'participants': 'participantes',
      'min': 'min',
      'Create Order': 'Criar pedido',
      'Discover': 'Descobrir',
      'Orders': 'Pedidos',
      'Streams': 'Streams',
      'Profile': 'Perfil',
      'All': 'Todos',
      'Live Streams': 'Transmissões ao vivo',
      'Earnings': 'Ganhos',
      'Settings': 'Configurações',
      'Content Creator': 'Criador de Conteúdo',
      'Language / 语言': 'Idioma / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'Plataforma MVP',
      'Sarah Chen': 'Sarah Chen',
      'In 1h': 'Em 1h',
      'In 23h': 'Em 23h',
      'In 2 days': 'Em 2 dias',
      'No pending orders': 'Nenhum pedido pendente',
      'No open orders': 'Nenhum pedido aberto',
      'No accepted orders': 'Nenhum pedido aceito',
      'No live streams': 'Nenhuma transmissão ao vivo',
      'No completed orders': 'Nenhum pedido concluído',
      'Central Park Concert Stream': 'Stream de Concerto no Central Park',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'Procurando alguém para transmitir o concerto ao ar livre que acontece no Central Park esta noite',
      'Central Park, NYC': 'Central Park, Nova York',
      'Food Market Tour': 'Tour do Mercado de Alimentos',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'Quero alguém para transmitir um tour guiado do Pike Place Market, mostrando vendedores locais e comida',
      'Pike Place Market, Seattle': 'Pike Place Market, Seattle',
      'Beach Sunset Yoga': 'Yoga do Pôr do Sol na Praia',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'Transmitir uma sessão pacífica de yoga ao pôr do sol na Praia de Santa Monica para entusiastas do bem-estar',
      'Santa Monica Beach, CA': 'Praia de Santa Monica, Califórnia'
    },
    'it': {
      'Search by location or description...': 'Cerca per posizione o descrizione...',
      'All Categories': 'Tutte le categorie',
      'Any Price': 'Qualsiasi prezzo',
      'Music': 'Musica',
      'Food': 'Cibo',
      'Travel': 'Viaggio',
      'Events': 'Eventi',
      'Fitness': 'Fitness',
      'Education': 'Educazione',
      'Available Orders': 'Ordini disponibili',
      'My Orders': 'I miei ordini',
      'Streaming Requests': 'Richieste di streaming',
      'Creator': 'Creatore',
      'Price': 'Prezzo',
      'Total Pool': 'Pool totale',
      'Accept Order': 'Accetta ordine',
      'Join Stream': 'Unisciti al stream',
      'Open': 'Aperto',
      'Live': 'In diretta',
      'Completed': 'Completato',
      'Unavailable': 'Non disponibile',
      'Pending': 'In sospeso',
      'Accepted': 'Accettato',
      'participants': 'partecipanti',
      'min': 'min',
      'Create Order': 'Crea ordine',
      'Discover': 'Scopri',
      'Orders': 'Ordini',
      'Streams': 'Stream',
      'Profile': 'Profilo',
      'All': 'Tutti',
      'Live Streams': 'Stream dal vivo',
      'Earnings': 'Guadagni',
      'Settings': 'Impostazioni',
      'Content Creator': 'Creatore di contenuti',
      'Language / 语言': 'Lingua / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'Piattaforma MVP',
      'Sarah Chen': 'Sarah Chen',
      'In 1h': 'Tra 1h',
      'In 23h': 'Tra 23h',
      'In 2 days': 'Tra 2 giorni',
      'No pending orders': 'Nessun ordine in sospeso',
      'No open orders': 'Nessun ordine aperto',
      'No accepted orders': 'Nessun ordine accettato',
      'No live streams': 'Nessun stream dal vivo',
      'No completed orders': 'Nessun ordine completato',
      'Central Park Concert Stream': 'Stream Concerto Central Park',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'Cerco qualcuno per trasmettere il concerto all\'aperto che si svolge al Central Park stasera',
      'Central Park, NYC': 'Central Park, New York',
      'Food Market Tour': 'Tour del Mercato Alimentare',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'Voglio qualcuno per trasmettere un tour guidato del Pike Place Market, mostrando venditori locali e cibo',
      'Pike Place Market, Seattle': 'Pike Place Market, Seattle',
      'Beach Sunset Yoga': 'Yoga Tramonto in Spiaggia',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'Trasmetti una sessione di yoga pacifica al tramonto a Santa Monica Beach per gli appassionati di benessere',
      'Santa Monica Beach, CA': 'Santa Monica Beach, California'
    },
    'ar': {
      'Search by location or description...': 'البحث حسب الموقع أو الوصف...',
      'All Categories': 'جميع الفئات',
      'Any Price': 'أي سعر',
      'Music': 'موسيقى',
      'Food': 'طعام',
      'Travel': 'سفر',
      'Events': 'أحداث',
      'Fitness': 'لياقة',
      'Education': 'تعليم',
      'Available Orders': 'الطلبات المتاحة',
      'My Orders': 'طلباتي',
      'Streaming Requests': 'طلبات البث',
      'Creator': 'منشئ',
      'Price': 'سعر',
      'Total Pool': 'المجموع الكلي',
      'Accept Order': 'قبول الطلب',
      'Join Stream': 'انضم للبث',
      'Open': 'مفتوح',
      'Live': 'مباشر',
      'Completed': 'مكتمل',
      'Unavailable': 'غير متوفر',
      'Pending': 'قيد الانتظار',
      'Accepted': 'مقبول',
      'participants': 'مشاركين',
      'min': 'دقيقة',
      'Create Order': 'إنشاء طلب',
      'Discover': 'اكتشف',
      'Orders': 'الطلبات',
      'Streams': 'البث',
      'Profile': 'الملف الشخصي',
      'All': 'الكل',
      'Live Streams': 'البث المباشر',
      'Earnings': 'الأرباح',
      'Settings': 'الإعدادات',
      'Content Creator': 'منشئ المحتوى',
      'Language / 语言': 'اللغة / Language',
      'TapLive': 'تاب لايف',
      'MVP Platform': 'منصة MVP',
      'Sarah Chen': 'سارة تشين',
      'In 1h': 'خلال ساعة',
      'In 23h': 'خلال 23 ساعة',
      'In 2 days': 'خلال يومين',
      'No pending orders': 'لا توجد طلبات معلقة',
      'No open orders': 'لا توجد طلبات مفتوحة',
      'No accepted orders': 'لا توجد طلبات مقبولة',
      'No live streams': 'لا يوجد بث مباشر',
      'No completed orders': 'لا توجد طلبات مكتملة',
      'Central Park Concert Stream': 'بث حفلة سنترال بارك',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'أبحث عن شخص لبث الحفلة الموسيقية في الهواء الطلق التي تحدث في سنترال بارك هذا المساء',
      'Central Park, NYC': 'سنترال بارك، نيويورك',
      'Food Market Tour': 'جولة سوق الطعام',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'أريد شخصًا لبث جولة إرشادية في سوق بايك بليس، عرض البائعين المحليين والطعام',
      'Pike Place Market, Seattle': 'سوق بايك بليس، سياتل',
      'Beach Sunset Yoga': 'يوغا غروب الشاطئ',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'بث جلسة يوغا هادئة عند غروب الشمس في شاطئ سانتا مونيكا لعشاق العافية',
      'Santa Monica Beach, CA': 'شاطئ سانتا مونيكا، كاليفورنيا'
    },
    'hi': {
      'Search by location or description...': 'स्थान या विवरण द्वारा खोजें...',
      'All Categories': 'सभी श्रेणियां',
      'Any Price': 'कोई भी कीमत',
      'Music': 'संगीत',
      'Food': 'भोजन',
      'Travel': 'यात्रा',
      'Events': 'घटनाएं',
      'Fitness': 'फिटनेस',
      'Education': 'शिक्षा',
      'Available Orders': 'उपलब्ध ऑर्डर',
      'My Orders': 'मेरे ऑर्डर',
      'Streaming Requests': 'स्ट्रीमिंग अनुरोध',
      'Creator': 'निर्माता',
      'Price': 'कीमत',
      'Total Pool': 'कुल पूल',
      'Accept Order': 'ऑर्डर स्वीकार करें',
      'Join Stream': 'स्ट्रीम में शामिल हों',
      'Open': 'खुला',
      'Live': 'लाइव',
      'Completed': 'पूर्ण',
      'Unavailable': 'अनुपलब्ध',
      'Pending': 'लंबित',
      'Accepted': 'स्वीकृत',
      'participants': 'प्रतिभागी',
      'min': 'मिनट',
      'Create Order': 'ऑर्डर बनाएं',
      'Discover': 'खोजें',
      'Orders': 'ऑर्डर',
      'Streams': 'स्ट्रीम',
      'Profile': 'प्रोफ़ाइल',
      'All': 'सभी',
      'Content Creator': 'सामग्री निर्माता',
      'Live Streams': 'लाइव स्ट्रीम',
      'Settings': 'सेटिंग्स',
      'Earnings': 'कमाई',
      'Discover Live Streams': 'लाइव स्ट्रीम खोजें',
      'Find and create location-based streaming experiences': 'स्थान-आधारित स्ट्रीमिंग अनुभव खोजें और बनाएं',
      'API Connected': 'API कनेक्टेड',
      'API Disconnected': 'API डिस्कनेक्टेड',
      'Active Streams Nearby': 'आस-पास सक्रिय स्ट्रीम',
      'No active streams nearby at the moment': 'इस समय आस-पास कोई सक्रिय स्ट्रीम नहीं',
      'No orders match your filters': 'आपके फिल्टर से कोई ऑर्डर मेल नहीं खाता',
      'You haven\'t created any orders yet': 'आपने अभी तक कोई ऑर्डर नहीं बनाया है',
      'Create Your First Order': 'अपना पहला ऑर्डर बनाएं',
      'What would you like to stream?': 'आप क्या स्ट्रीम करना चाहेंगे?',
      'Describe the streaming experience you want...': 'जो स्ट्रीमिंग अनुभव आप चाहते हैं उसका वर्णन करें...',
      'Enter location (e.g., San Francisco, CA)': 'स्थान दर्ज करें (जैसे: दिल्ली, भारत)',
      'Select duration': 'अवधि चुनें',
      'Select category': 'श्रेणी चुनें',
      'Get Current Location': 'वर्तमान स्थान प्राप्त करें',
      'Creating...': 'बना रहे हैं...',
      'Central Park Concert Stream': 'सेंट्रल पार्क कॉन्सर्ट स्ट्रीम',
      'Looking for someone to stream the outdoor concert happening at Central Park this evening': 'आज शाम सेंट्रल पार्क में हो रहे आउटडोर कॉन्सर्ट को स्ट्रीम करने के लिए किसी की तलाश',
      'Central Park, NYC': 'सेंट्रल पार्क, न्यूयॉर्क',
      'Food Market Tour': 'फूड मार्केट टूर',
      'Want someone to stream a guided tour of Pike Place Market, showcasing local vendors and food': 'पाइक प्लेस मार्केट का गाइडेड टूर स्ट्रीम करने के लिए किसी को चाहिए, जो स्थानीय विक्रेताओं और भोजन को दिखाए',
      'Pike Place Market, Seattle': 'पाइक प्लेस मार्केट, सिएटल',
      'Beach Sunset Yoga': 'बीच सनसेट योग',
      'Stream a peaceful sunset yoga session at Santa Monica Beach for wellness enthusiasts': 'स्वास्थ्य उत्साही लोगों के लिए सांता मोनिका बीच पर शांतिपूर्ण सनसेट योग सत्र स्ट्रीम करें',
      'Santa Monica Beach, CA': 'सांता मोनिका बीच, कैलिफोर्निया',
      'Success': 'सफलता',
      'Error': 'त्रुटि',
      'Connection Error': 'कनेक्शन त्रुटि',
      'Failed to connect to the server': 'सर्वर से कनेक्ट करने में विफल',
      'Order accepted successfully!': 'ऑर्डर सफलतापूर्वक स्वीकार किया गया!',
      'Failed to accept order': 'ऑर्डर स्वीकार करने में विफल',
      'Joining Stream': 'स्ट्रीम में शामिल हो रहे हैं',
      'Opening live stream...': 'लाइव स्ट्रीम खोल रहे हैं...',
      'Manage your streaming orders and track their progress': 'अपने स्ट्रीमिंग ऑर्डर का प्रबंधन करें और उनकी प्रगति को ट्रैक करें',
      'No orders found': 'कोई ऑर्डर नहीं मिला',
      'Your orders will appear here once you create them': 'आपके ऑर्डर बनाने के बाद यहाँ दिखाई देंगे',
      'Select Language / 选择语言': 'भाषा चुनें / Select Language',
      'Active': 'सक्रिय',
      'Language / 语言': 'भाषा / Language',
      'TapLive': 'TapLive',
      'MVP Platform': 'MVP प्लेटफॉर्म',
      'Sarah Chen': 'सारा चेन',
      'Tomorrow': 'कल',
      'Now': 'अब',
      'In 1h': '1 घंटे में',
      'In 23h': '23 घंटे में',
      'In 2 days': '2 दिन में',
      'No pending orders': 'कोई लंबित ऑर्डर नहीं',
      'No open orders': 'कोई खुले ऑर्डर नहीं',
      'No accepted orders': 'कोई स्वीकृत ऑर्डर नहीं',
      'No live streams': 'कोई लाइव स्ट्रीम नहीं',
      'No completed orders': 'कोई पूर्ण ऑर्डर नहीं'
    }
  };

export function TranslatedText({ children, className }: TranslatedTextProps) {
  const { currentLanguage } = useTranslation();
  
  const translation = translations[currentLanguage]?.[children] || children;
  
  return <span className={className}>{translation}</span>;
}

// Hook to get translated text for form fields using the same translations object
export function useTranslatedText(text: string): string {
  const { currentLanguage } = useTranslation();
  console.log('useTranslatedText - currentLanguage:', currentLanguage, 'text:', text);
  const translation = translations[currentLanguage]?.[text] || text;
  console.log('useTranslatedText - translation result:', translation);
  return translation;
}